### ISSUE TITLE
Annotate translated models (using globalize2).

### ISSUE THREAD

**Issue by pupeno** [ctran/annotate_models#11]
When using globalize2 to translate a model, not all fields of the model are actually stored in the table. Some are stored on a separate table called <model_name>_translations. Would it be possible to scan those tables too and annotate the correct model?

For example, if I have a model called Page I have two tables, pages and page_translations. page_translations have the typical id, created_at, updated_at as well as a <model>_id field, in this case page_id and locale fields, that should also be ignored. All other fields can be accessed on the Page model so having it annotated would be useful.

**Comment by ctran** [comment]
I'm not sure if this is even applicable anymore.
