### ISSUE TITLE
Could not find generator annotate:install.

### ISSUE THREAD

**Issue by ocolot** [ctran/annotate_models#124]
Annotate works well, but for some reason the
    rails g annotate:install
provides a fancy 
    Could not find generator annotate:install.

I am on rails 4, with annotate >=2.5.0 in my Gemfile.

**Comment by narender2031** [comment]
I am still facing this issue anyone have an idea about it

**Comment by axhamre** [comment]
Still an issue, April 2020. Both what's in the README and suggested as first comment. Rails 6.0.
