### ISSUE TITLE
support active model serializers

### ISSUE THREAD

**Issue by simonweil** [ctran/annotate_models#148]
Please add support for Active Model Serializers Gem.
https://github.com/rails-api/active_model_serializers

**Comment by rusterholz** [comment]
+1! Now that Serializers are included by default in Rails 4, formally adding support for this would be especially desirable. Can this be revisited? Our team would love it.

@drewda's fork appears to have support for this, so AFAIK it should be as simple as pulling in his fork and fixing any borked regressions.

**Comment by drewda** [comment]
My PR is features complete, but I didn't add any test coverage. Help from
someone more familiar with the test suite would be great.

**Comment by rusterholz** [comment]
@ctran It's been over a year since this issue was opened, and almost five months since @drewda's PR. Could that be merged?

**Comment by ctran** [comment]
I don't remember there was a PR on this.

**Comment by drewda** [comment]
Two duplicate PRs:

* https://github.com/ctran/annotate_models/pull/213
* https://github.com/ctran/annotate_models/pull/219

In any case, there's now support for serializers.

**Comment by ctran** [comment]
Cool!

**Comment by simonweil** [comment]
Great, thanks!
