### ISSUE TITLE
Command name "annotate" conflicts with gd2, bazaar

### ISSUE THREAD

**Issue by cabo** [ctran/annotate_models#153]
Not a great choice for the name of the command line tool.
(Yes, the other two packages have to fix this, too.)

How about annomo or some such.  Shorter, too.

**Comment by cabo** [comment]
Apparently, the binaries live in different places on your system.
It's still a lottery which of the ones you actually get.
For your reference, here is how the installation fails when gd2 or bazaar are installed (the command here was `gem update`):

```
Updating annotate
annotate's executable "annotate" conflicts with /opt/local/bin/annotate
Overwrite the executable? [yN]  n
ERROR:  Error installing annotate:
	"annotate" from annotate conflicts with /opt/local/bin/annotate
```

**Comment by ctran** [comment]
There's not much I can do at this point.  There are workarounds that you can employ (rename your annotate, use rbenv, etc).  The current binary is already used by existing users so renaming is out of the question.  Besides, it's a good descriptive name.
