### ISSUE TITLE
# -*- SkipSchemaAnnotations can not work .

### ISSUE THREAD

**Issue by songjiayang** [ctran/annotate_models#167]
error message `Unable to annotate user.rb: stack level too deep` when i run migrate .
i add `# -*- SkipSchemaAnnotations` in user.rb, but it not work yet , but 
`skip_on_db_migrate=1 rake db:migrate` work well . thanks

**Comment by gbenedict** [comment]
I'm having the same issue with `# -*- SkipSchemaAnnotations` – it doesn't skip the annotation.

**Comment by ctran** [comment]
Please provide more details: your version of ruby and annotate, Gem file, any other useful information.
Also the symptoms of why you think it doesn't work.

**Comment by gbenedict** [comment]
ruby: 2.1.2p95
gem: 2.6.5

I have added `# -*- SkipSchemaAnnotations` to several models, but the annotations are still added to those models during migrations or running annotate directly. The models I am trying to skip are in a subdirectory for organization. They also use STI and inheritance (`WorkflowActionCallExternalApi < WorkflowAction`).
