### ISSUE TITLE
'already initialized constant' warnings

### ISSUE THREAD

**Issue by eval** [ctran/annotate_models#169]
I'm getting the following errors when running `bundle exec annotate` in my rails project:

```
/Users/gert/tmp/annotate-issue/blog/app/models/person.rb:2: warning: already initialized constant Person::A
/Users/gert/tmp/annotate-issue/blog/app/models/person.rb:2: warning: previous definition of A was here
Annotated (1): Person
```

While it doesn't seem to have any impact on the annotations, it looks like something is wrong.

I created a template to reproduce the issue: https://gist.github.com/eval/9410525
(try bundling `v2.6.1` and the warnings don't appear).

Reverting https://github.com/ctran/annotate_models/commit/a89c8d9328f95742b22fd065a7e7248adb6b4996 locally seems to fix it.

ruby -v: `ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin13.0]`
rails -v: `Rails 4.1.0.rc1`

**Comment by esbanarango** [comment]
I'm still having the same issue that @kuroda explained. 
__parent classes of Single Table Inheritance (STI)__.
