### ISSUE TITLE
Deannotation errors on non-ActiveRecord models

### ISSUE THREAD

**Issue by theoretick** [ctran/annotate_models#172]
During deannotation, errors are thrown with non-AR models in models directory, including ActiveRecord::Observer objects:
```ruby
$ annotate --delete
Unable to deannotate city_observer.rb: undefined method `<' for nil:NilClass
Unable to deannotate error_response.rb: undefined method `<' for nil:NilClass
Removed annotations from: City, State, User, ...
```
The models:
```ruby
class CityObserver < ActiveRecord::Observer
end
```
```ruby
class ErrorResponse
    attr_accessor :messages, :status_code
    ...
end
```

This issue is minor as all other models are correctly deannotated

**Comment by nagarajan-techhue** [comment]
brew install homebrew/dupes/grep
Error: undefined method `deprecated_option' for Grep:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-dupes/grep.rb:12
/usr/local/Library/Homebrew/formulary.rb:65:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:185:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:27:in `install'
/usr/local/Library/brew.rb:106:in `send'
/usr/local/Library/brew.rb:106
