### ISSUE TITLE
Factories in subdirectories aren't annotated

### ISSUE THREAD

**Issue by guapolo** [ctran/annotate_models#184]
Factories in `spec/factories` subdirectories aren't annotated.

I tend to namespace many of my models, and preserve the same structure of file structure for factories, like `/spec/factories/a_namespace/a_model_factory.rb`.

It would be nice to have this feature added.

**Comment by pelletencate** [comment]
Same goes for annotations in serializers in subdirectories. We have our API serializers in a subdirectory, they don't get annotated.
