### ISSUE TITLE
Annotation of models in Rails Engine

### ISSUE THREAD

**Issue by bobbdelsol** [ctran/annotate_models#190]
Hey, as best as i can tell, you don't recognize models inside a rails engine.

So the module Enginename    Wrapper is throwing you off.

Also, they're pushed down on level in models  models/engingname/....

**Comment by OneDivZero** [comment]
Yes that would be a really nice feature!

**Comment by cheef** [comment]
+1

**Comment by ctran** [comment]
It should now work.
