### ISSUE TITLE
Limit annotation line length to 80 characters

### ISSUE THREAD

**Issue by ressu** [ctran/annotate_models#192]
Currently annotate doesn't really care about how long the annotated lines are. Since I'm a bit pedantic and like to keep running rubocop over my source files, I keep hitting a problem with certain models where annotations exceed the line length of 80 characters.

Since 80 characters is a common practice in many places it would be nice if annotate_models also had an option to limit the line length.

Also, it's worth mentioning that while there are ways to avoid this in models, the annotations in routes are pretty consistently over 80 characters. There is no real way of avoiding this, except not annotating routes.

**Comment by glittershark** [comment]
Would it be possible to add a configuration option for comment template in the meantime so we could put the necessary `# rubocop:disable Style/LineLength` comments as part of annotate?

**Comment by CyborgMaster** [comment]
And a `# rubocop:enable Style/LineLength` at the bottom too so we don't turn it off for the whole file.

**Comment by glittershark** [comment]
Looked into implementing this myself and shortly after getting it all to work I realized #225 exists :smile: @CyborgMaster if you run `annotate` after the develop branch you can specify `wrapper_open="rubocop:disable Metrics/LineLength" wrapper_close="rubocop:enable Metrics/LineLength"` as arguments to the rake task

**Comment by CyborgMaster** [comment]
@glittershark, that's pretty awesome!!!  Thanks for the tip.  I'll try it now.

**Comment by dduqueti** [comment]
@glittershark @CyborgMaster Thank you for this. I did found an issue, the initial annotation added the `wrapper_open` and `wrapper_close` texts but after adding a new field in a new migration, they were lost. Did you experienced this?

**Comment by CyborgMaster** [comment]
Yes, we have that too.  There seems to be a bug where the rake task tied to the migrations seems to skip all the configuration.   If I run `annotate --force` after the migration if puts it back.

**Comment by dduqueti** [comment]
@CyborgMaster Thanks!
