### ISSUE TITLE
Usage outside rails - Sinatra/ActiveRecord

### ISSUE THREAD

**Issue by ktaragorn** [ctran/annotate_models#199]
I copied the `auto_annotate_models.rake` file from a rails project, over to our sinatra app, set the `model_dir` in it to `app/rds_models` and tried `annotate` and `annotate --model-dir app/rds_models`. Both of these led to 

```
I, [2014-07-10T15:18:34.444536 #5473]  INFO -- : development
/Users/karthikt/.rvm/gems/ruby-2.1.2/gems/annotate-2.6.5/lib/annotate.rb:100:in `eager_load': undefined method `version' for Rails:Module (NoMethodError)
        from /Users/karthikt/.rvm/gems/ruby-2.1.2/gems/annotate-2.6.5/bin/annotate:155:in `<top (required)>'
        from /Users/karthikt/.rvm/gems/ruby-2.1.2/bin/annotate:23:in `load'
        from /Users/karthikt/.rvm/gems/ruby-2.1.2/bin/annotate:23:in `<main>'
        from /Users/karthikt/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
        from /Users/karthikt/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

I had to do `model_dir=app/rds_models rake annotate_models` to finally get it working. This is from going through the code, and seeing the `ENV[]` values being used to initialize the options.

**Comment by betesh** [comment]
:+1: 

I suspect I'm having the same problem.  When I run `annotate --model-dir=lib/models` in a sinatra app, I get:

    .../annotate-2.6.5/lib/annotate.rb:142:in `block in fallback': undefined method `blank?' for nil:NilClass (NoMethodError)
