### ISSUE TITLE
Doesn't find models in subdirectories correctly

### ISSUE THREAD

**Issue by michael-moroku** [ctran/annotate_models#200]
I have the following structure:

app/models/sub1/sub2/sub3

When annotating it correctly annotates models in sub1 classes but fails to annotate models in sub2 or sub3.

The error message says: Unable to annotate sub1/sub2/sub3/model.rb: cannot load such file -- path_to_app/app/models/sub2/sub3/model

**Comment by PaBLoX-CL** [comment]
I'm having this problem too:

    Unable to annotate data_values/text/code_phrase.rb: cannot load such file -- /home/pablo/code/rails/simple-openehr/app/models/text/code_phrase

Which is weird, because I don't understand why it looks on `app/models/text/code_phrase`
PS.- Why is this issue closed?

**Comment by PaBLoX-CL** [comment]
```
# /vendor/bundle/gems/annotate-2.6.5/lib/annotate/annotate_models.rb @ line 396 AnnotateModels.get_loaded_model:
[1] pry(AnnotateModels)> model_path
=> "data_values/text/code_phrase"
[2] pry(AnnotateModels)> ActiveSupport::Inflector.camelize(model_path)
=> "DataValues::Text::CodePhrase"
[3] pry(AnnotateModels)> ActiveSupport::Inflector.constantize(ActiveSupport::Inflector.camelize(model_path))
LoadError: Unable to autoload constant DataValues::Text::CodePhrase, expected /home/pablo/code/rails/simple-openehr/app/models/data_values/text/code_phrase.rb to define it
from /home/pablo/code/rails/simple-openehr/vendor/bundle/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:495:in `load_missing_constant'
```
```ruby
# app/models/data_values/text/code_phrase.rb
class CodePhrase < ActiveRecord::Base
  belongs_to :CodePhraseable, polymorphic: true
end
# config/application.rb
config.autoload_paths += %W(#{config.root}/app/models/data_values/text)
```

Then after the rescue block:
```
    395:   rescue
 => 396:     binding.pry
```
[1] pry(AnnotateModels)> model_path
=> "text/code_phrase"t

**Comment by ctran** [comment]
Have you tried to specify the "--model-dir" option?

**Comment by CyborgMaster** [comment]
Further investigation seems to indicate that the problem only occurs when you have STI classes with the base class in a subdirectory.  

From my previous post, my `reminder_due_trigger.rb` file inherits from `trigger.rb`, which might be why it's trying to load it from the `app/models/triggers/` directory, but in my case triggers are stored in `app/models/comm_engine/triggers/`.  

It seems to find models that aren't STI in subdirectories just fine.  Ex: it annotates `/app/models/sync/appointment.rb` just fine.

**Comment by CyborgMaster** [comment]
I'm trying to mess with the `--model-dir` option, but no luck so far.

**Comment by CyborgMaster** [comment]
I think, I've figured it out, working on a pull request now.

**Comment by CyborgMaster** [comment]
I've got a pull request open that fixes this bug.  #232
