### ISSUE TITLE
Rails 4.2.0.beta2

### ISSUE THREAD

**Issue by fmbiete** [ctran/annotate_models#212]
Upgrading to Rails 4.2.0.beta2 changes some already annotated models:

```
-#  size_pagination     :integer          default(20), not null
+#  size_pagination     :integer          default("20"), not null
-#  has_vpn             :boolean          default(FALSE)
+#  has_vpn             :boolean          default("f")
```

Only integer and boolean seems to change.

**Comment by JanStevens** [comment]
*bump* any update for rails 4.2? All our annotations changed (massive diff) just because of a rails upgrade. It would be nice to have a constant annotation independent of the rails version.

It seems that the column defaults are now all converted to string?

```
-#  config_properties :hstore           default({}), not null
+#  config_properties :hstore           default(""), not null
```

**Comment by CyborgMaster** [comment]
I'm still getting this issue on rails 4.2.0.

My booleans changed as follows:
``` diff
-#  disabled    :boolean          default(TRUE), not null
-#  simple      :boolean          default(FALSE), not null
+#  disabled    :boolean          default("1"), not null
+#  simple      :boolean          default("0"), not null
```

my integers like this:
``` diff
-#  appt_email_done             :integer          default(0), not null
+#  appt_email_done             :integer          default("0"), not null
```

and my text fields like this:
``` diff
-#  body            :text
+#  body            :text(65535)
```

It seems like default values are being converted to strings (or not converted back into their proper ruby types) before being added to the comment.
