### ISSUE TITLE
Annotation does not update when using change_column_null

### ISSUE THREAD

**Issue by thatRailsGuy** [ctran/annotate_models#224]
When doing a migration which changes whether a column is nullable does not result in updated annotation when using automatic annotation.
    class MakePasswordUpdatedAtNotNull < ActiveRecord::Migration
      def change
        change_column_null :users, :password_updated_at, false
      end
    end

**Comment by ctran** [comment]
This may be related to #205

**Comment by ctran** [comment]
Unable to reproduce this with latest version.
