### ISSUE TITLE
Fixtures in directories

### ISSUE THREAD

**Issue by andrew2005** [ctran/annotate_models#228]
I used the rails model generator as follows:

    rails generate model Parent::Child name:string
      invoke  active_record
        create    db/migrate/20150117095251_create_parent_children.rb
        create    app/models/parent/child.rb
        create    app/models/parent.rb
        invoke    minitest
          create      test/models/parent/child_test.rb
          create      test/fixtures/parent/children.yml

As you can see it creates fixture file `children.yml` under the `parent` directory.

When I run annotate, it correctly annotates the mode and the unit test, but not the fixture. If I move and rename the fixture to to `test/fixtures/parent_children.yml`, annotate works successfully. Whatever smarts is being applied to the model and unit test isn't being applied to the fixture.

Happy to send a pull request if you point out where the issue is. I had a bit of a look but couldn't find it.

I'm running rails 4.2 with annotate 2.6.5. Thanks for the great gem!

**Comment by djhopper01** [comment]
Just to add some extra info here, here's the commit in Rails that seems to introduce fixture support for namespaced models: https://github.com/rails/rails/commit/8ec085bf1804770a547894967fcdee24087fda87

**Comment by plicjo** [comment]
Hey, I've got a pull-request fix for this at https://github.com/ctran/annotate_models/pull/255

The gem was trying to annotate a fixture living at filepath ```'test/fixtures/parent_children.yml'```.

Rails generates nested models as such: ```'test/fixtures/parent/children.yml'```

The fix targets the correct filepath for annotation. This was quite an edge-case!

**Comment by andrew2005** [comment]
Awesome, thanks guys!

**Comment by plicjo** [comment]
But you didn't merge it, Andrew?
