### ISSUE TITLE
Request: foreign key support

### ISSUE THREAD

**Issue by noinkling** [ctran/annotate_models#236]
Now that Rails (>4.2) has support for database foreign keys, it would be nice to have an option for seeing these in the annotations.

**Comment by noinkling** [comment]
`ActiveRecord::Base.connection.supports_foreign_keys?` can be used to check if the db supports them (I think only sqlite doesn't), then `ActiveRecord::Base.connection.foreign_keys("table_name")` can be used to get a list of them for any particular table.

**Comment by franklsf95** [comment]
+1 would be really convenient!
