### ISSUE TITLE
Annotate on different machines is producing different comments

### ISSUE THREAD

**Issue by LimeBlast** [ctran/annotate_models#238]
We're running annotate on a project with around 60 models in it.

So far as I can tell, the gem is working just fine, as all of the models are getting annotated correctly - except that, depending on which machine is doing the annotation, the annotation comments keep changing.

To give you an example of what I mean, one person will run it, and get:

    #  summary             :string

Then someone else will run it, and they'll get

    #  summary             :string(255)

or the order of the descimal will change, i.e. one person:

    #  cost                  :decimal(8, 3)    default(0.0), not null

while someone else:

    #  cost                  :decimal(3, 8)    default(0.0), not null

These are on exactly the same models, having run exactly the same migrations.

Any ideas? Cheers.

**Comment by u2** [comment]
I have the same problem on my computer.I have two models.
```ruby
#schema.rb
  create_table "orders", force: true do |t|
    t.decimal  "total_price",               precision: 10, scale: 2, default: 0.02
    t.decimal  "actual_price",              precision: 10, scale: 2, default: 0.01
    t.decimal  "paid_money",                precision: 10, scale: 2, default: 0.0
end

  create_table "car_orders", force: true do |t|
    t.integer  "user_id"
    t.decimal  "total_price",         precision: 10, scale: 0
    t.decimal  "actual_price",        precision: 10, scale: 0
    t.decimal  "paid_money",          precision: 10, scale: 0
end
```
But the annotation is different.
```ruby
#order.rb
# == Schema Information
#
# Table name: orders
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  total_price   :decimal(10, 2)   default(0.02)
#  actual_price  :decimal(10, 2)   default(0.01)
#  paid_money    :decimal(10, 2)   default(0.0)

#car_order.rb

# == Schema Information
#
# Table name: car_orders
#
#  id                  :integer          not null, primary key
#  user_id             :integer
#  total_price         :integer
#  actual_price        :integer
#  paid_money          :integer
```
After `annotate --force`, the same result.

**Comment by u2** [comment]
It's ok after update to 2.6.8. :smile:
