### ISSUE TITLE
[REQUEST] annotate enum values and labels

### ISSUE THREAD

**Issue by francescob** [ctran/annotate_models#239]
It would be great if the the gem could generate annotation for enum types introduced in rails 4.1 (or using the gem enumerize)

**Comment by palexvs** [comment]
Seems like this feature has not developed yet, am I right?
annotate v2.7.1 returns:
```
#  type                  :string(2)       not null
```

for table:
```
CREATE TABLE `t1` (
...
  `type` enum('v1','v2','v3','v4','v5') NOT NULL,
....
)
```
