### ISSUE TITLE
Annotating routes after `rails g scaffold`

### ISSUE THREAD

**Issue by vfonic** [ctran/annotate_models#245]
I wanted to add "routes" => "true" (or something similar) to auto_annotate_models.rake, but couldn't figure out how to add it. There are some commands that change routes.rb and I'd love to be able to just run rake db:migrate that will also annotate routes again if needed.

**Comment by ctran** [comment]
You'll need to generate a file that looks like this https://github.com/ctran/annotate_models/blob/develop/lib/generators/annotate/templates/auto_annotate_models.rake in lib/tasks/auto_annotate_routes.rake

**Comment by vfonic** [comment]
Thanks for reply @ctran. The issue is that I can't figure out how to specify the setting that will also make sure that `routes.rb` is annotated. Here's my `auto_annotate_models.rake`:

```ruby
# NOTE: only doing this in development as some production environments (Heroku)
# NOTE: are sensitive to local FS writes, and besides -- it's just not proper
# NOTE: to have a dev-mode tool do its thing in production.
if Rails.env.development?
  task :set_annotation_options do
    # You can override any of these by setting an environment variable of the
    # same name.
    Annotate.set_defaults({
      'exclude_factories'    => "false",
      'exclude_fixtures'     => "false",
      'exclude_tests'        => "false",
      'force'                => "false",
      'format_bare'          => "false",
      'format_markdown'      => "true",
      'format_rdoc'          => "false",
      'ignore_model_sub_dir' => "false",
      'include_version'      => "false",
      'model_dir'            => "app/models",
      'position_in_class'    => "before",
      'position_in_factory'  => "before",
      'position_in_fixture'  => "before",
      'position_in_routes'   => "before",
      'position_in_test'     => "before",
      'require'              => "",
      'routes'               => "true",
      'r'                    => "true",
      'show_indexes'         => "true",
      'show_migration'       => "true",
      'simple_indexes'       => "false",
      'skip_on_db_migrate'   => "false",
      'classified_sort'      => "true",
      'trace'                => "true",
    })
  end

  Annotate.load_tasks
end
```

Notice the unsuccessful tries: `'routes' => "true" and 'r' => "true"`

I've also forked the gem and tried to figure out what could be the issue on my own, but with no success.

**Comment by ctran** [comment]
Sorry for taking a while but this is now supported.

**Comment by vfonic** [comment]
Thanks! I'm looking forward for the release! :)
