### ISSUE TITLE
brew gd | /usr/local/Cellar/gd/2.1.0_2/bin/annotate

### ISSUE THREAD

**Issue by paulomcnally** [ctran/annotate_models#256]
/Users/paulomcnally/.rbenv/shims/annotate
    /Users/paulomcnally/.rbenv/versions/2.2.2/bin/annotate
    /Users/paulomcnally/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/doc/annotate-2.6.10/ri/lib/generators/annotate
    /Users/paulomcnally/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/annotate-2.6.10/bin/annotate
    /Users/paulomcnally/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/annotate-2.6.10/lib/annotate
    /Users/paulomcnally/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/annotate-2.6.10/lib/generators/annotate
    /usr/local/bin/annotate
    /usr/local/Cellar/gd/2.1.0_2/bin/annotate

**Comment by ctran** [comment]
Is this supposed to mean something?

**Comment by paulomcnally** [comment]
It means there is a MacOS binary called as binary gem
