### ISSUE TITLE
`annotate -e` doesn't skip serializers by default

### ISSUE THREAD

**Issue by wli** [ctran/annotate_models#270]
`annotate -e` doesn't skip serializers by default

However, `annotate -i -k -e serializers` does work.

Looks like `exclude_serializers` missing from this list of flags: https://github.com/ctran/annotate_models/blob/c479e5af2e2eb7bac98fa6787b352030549daeaa/lib/annotate.rb#L25

**Comment by wli** [comment]
I'm running 2.6.10 by the way.

**Comment by ctran** [comment]
Is this still an issue with the latest version?
