### ISSUE TITLE
annotate is not run automatically on rollback

### ISSUE THREAD

**Issue by rhymes** [ctran/annotate_models#276]
Since you run annotate on rake db:migrate, shouldn't it be run as well on rake db:rollback ?

**Comment by ctran** [comment]
This doesn't seem like a useful enough use case.  Typically you'd rely on your version control tool to revert the changes anyway?

**Comment by rhymes** [comment]
I understand, it's definitely not a priority, I just noticed it yesterday and thought it might have been an oversight

**Comment by ctran** [comment]
I'll take a PR though :-)

**Comment by rhymes** [comment]
@ctran maybe I'm mistaken but according to this https://github.com/ctran/annotate_models/blob/develop/lib/tasks/migrate.rake#L8 isn't it supposed to run on rollback as well?

**Comment by alexch** [comment]
I think it's a good idea.

On Thu, Sep 10, 2015 at 2:03 AM, rhymes <notifications@github.com> wrote:

> I understand, it's definitely not a priority, I just noticed it yesterday
> and thought it might have been an oversight
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ctran/annotate_models/issues/276#issuecomment-139157522>
> .
>



-- 
Alex Chaffee - alexch@gmail.com
http://alexchaffee.com
http://codelikethis.com
http://twitter.com/alexch

**Comment by alexch** [comment]
@rhymes yeah, that's what I thought. Is this just a documentation glitch or is migrate-on-rollback failing for you?

**Comment by rhymes** [comment]
@alexch @ctran sorry guys, I'm using 2.6.10 and that bit has not been released yet. That's why I got confused. No worries, I'll just wait for the next release or use the git version. We can close the issue ;-)
