### ISSUE TITLE
Option to skip table name

### ISSUE THREAD

**Issue by GregPK** [ctran/annotate_models#277]
In Rails 99% of the time the table is the same name as the model, I would like an option to skip that in the output. 

That would also mean not indenting the columns (at least I think so). 

Note: would be happy to take a whack at this, just thought I mention it here in the case it's in the works or I'm blind and the option is already there.

**Comment by ctran** [comment]
PR is welcome.

**Comment by ctran** [comment]
I'm closing this unless you're willing to make this change.

**Comment by GregPK** [comment]
Sorry, hadn't had much time. You can close it for now.
