### ISSUE TITLE
Skip column size for text columns

### ISSUE THREAD

**Issue by letronje** [ctran/annotate_models#278]
For the same table and column, we are seeing 2 different comments for the same 'text' column in mysql

We are running rails 4.2.4

On 1 machine(running mysql 5.5.32), the comment generated is 
# description                          :text(16777215)

and on 2 other dev machines( running mysql  5.5.34 and 5.5.44) , it generates
#  description                          :text(65535)

As per mysql on all machines, the column type is "text".

Could it be the different versions of mysql  ?

Is there any way to prevent column size(or whatever that number is) from being part of the auto generated comment ?

**Comment by andrewek** [comment]
A similar issue occurs between different versions of PostgreSQL. Using Postgres 9.4.1 on my linux machine produces `name :string`, whereas using the Postgres app on my Mac produces `name :string(255)`.

**Comment by ctran** [comment]
This seems like an issue with Rails - https://github.com/rails/rails/issues/19001

**Comment by ctran** [comment]
This is now an option.
