### ISSUE TITLE
Annotate breaks with money-rails gem monetize command

### ISSUE THREAD

**Issue by noctivityinc** [ctran/annotate_models#279]
If I have something like this:

    monetize :budget

in my model, annotate will report:

     Unable to annotate board.rb: Board already has a monetized attribute called 'budget'
     Nothing annotated.

But if I comment out that line it runs fine and annodates the model.

**Comment by sirvine** [comment]
I have also been having this issue for a while—wasn't sure whose court this belongs in, since money-rails is raising the error here: https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_record/monetizable.rb#L267

**Comment by ctran** [comment]
Can't seem to reproduce this with the latest version (on github).

**Comment by joshleblanc** [comment]
Just in case anyone else stumbles upon this 8 years later - run `rails tmp:cache:clear`. Bootsnap is likely caching something it shouldn't be.
