### ISSUE TITLE
'already initialized constant' warnings when models are in additional configured auto load roots

### ISSUE THREAD

**Issue by bughit** [ctran/annotate_models#281]
###### to repro:
1. `git clone git@github.com:bughit/annotate_test.git`
2.  `rake db:migrate`

###### how to configure additional auto load roots:
`config.eager_load_paths.concat Dir["#{config.root}/app/models/additional_roots/**/"]`

**Comment by ctran** [comment]
Can you clarify what the third-line does there?

config.eager_load_paths.concat Dir["#{config.root}/app/models/additional_roots/**/"]

**Comment by bughit** [comment]
modules in eager_load_paths are eager loaded in production and auto loaded in development

if you have class Foo in app/models/additional_roots/sub1/sub2/foo.rb and you refer to it somewhere `Foo.new` it will be autoloaded.

**Comment by ctran** [comment]
I'm aware of that.  I'm asking for more details in your report since it's kind of skimmed :question:

**Comment by bughit** [comment]
1. and 2. in the first post are exact repro directions, you should run them.

The `config` line is just an operational definition of  "additional configured auto load roots"

**Comment by ctran** [comment]
Thanks.  I'll take a look

**Comment by bughit** [comment]
have a question about the fix.  I haven't debugged this, but isn't the source of the problem that some model files are being loaded twice?  If so, could that not cause other problems?  Would it not better to try to avoid this double loading rather than just silence the warning.

**Comment by ctran** [comment]
It's tricky to know whether a model inside a file is already loaded due to
auto-loading magic, complicated further by pre-loaded paths. If you know a
better way to detect that, let me know.

**Comment by 0x01f7** [comment]
@ctran I think the tricky is to use `$LOAD_PATH`. The code below should work:

```ruby
def get_model_class(file)
  # ...
  get_loaded_model(model_path) || raise(BadModelFileError.new)
  # ...
end

def get_loaded_model_fixed(model_path, file)
  klass = get_loaded_model(model_path)
  return klass if klass

  absolute_file = File.expand_path(file)
  model_paths = $LOAD_PATH.select { |load_path| absolute_file.include?(load_path) }.map { |load_path| absolute_file.sub(load_path, '').sub(/^\//, '').sub(/\.rb$/, '') }
  model_paths.map { |model_path| get_loaded_model(model_path) }.find { |loaded_model| !loaded_model.nil? }
end
```
