### ISSUE TITLE
Unable to annotate foreign_keys is not implemented

### ISSUE THREAD

**Issue by overdrivemachines** [ctran/annotate_models#282]
Out of the blue, I'm unable to annotate anymore. I get the error:
Unable to annotate app/models/property.rb: foreign_keys is not implemented

What am I doing wrong?

**Comment by ctran** [comment]
Is there any stack trace?  What version are you using?

**Comment by overdrivemachines** [comment]
How do I view the stack trace?
Also I get the same error for all my models.
Please I need a fix.

Here are the versions:
annotate v2.6.10
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
Rails 4.2.4

**Comment by ngelx** [comment]
+1
