### ISSUE TITLE
position_in_routes: after

### ISSUE THREAD

**Issue by anggiaj** [ctran/annotate_models#285]
Why `rake annotate_routes` with `position_in_routes: 'after'` still add comments on the top of `routes.rb` instead on the bottom?

**Comment by ctran** [comment]
What version are you using?  Some additional information would be helpful.

**Comment by anggiaj** [comment]
`2.6.10`

**Comment by ctran** [comment]
I'm not seeing the problem after running this against the latest version:

    position_in_routes=after rake annotate_routes
