### ISSUE TITLE
annotate additional subdirectories 

### ISSUE THREAD

**Issue by djsegal** [ctran/annotate_models#286]
a scaffold generates files in the following rspec subdirectories:
  + `spec/models`
  + `spec/controllers`
  + `spec/requests`
  + `spec/routing`

currently, only `spec/models` is annotated. is there a way to annotate the other three?

**Comment by ctran** [comment]
A PR is welcome!  What version of rails does this?

**Comment by djsegal** [comment]
I'm testing it now. I'm working with a Rails 5 API

**Comment by djsegal** [comment]
I just finished the PR and tested it with test_unit and rspec: https://github.com/ctran/annotate_models/pull/287

**Comment by djsegal** [comment]
@ctran is there anything more I can do to help?

**Comment by ctran** [comment]
Sorry, I will take a look tomorrow.

**Comment by ctran** [comment]
This is now merged into "develop".  It will be part of the next release.
