### ISSUE TITLE
Annotate.load_tasks raising no build task error for 'annotate_models' for Engines

### ISSUE THREAD

**Issue by djsegal** [ctran/annotate_models#295]
----------

Related to issue: #190 

+ Error is for non-mountable engines
+ Previous workaround was running `annotate` in the `spec/dummy` subdirectory (i.e. not having annotate run after every `db:migrate`)

----------

```
❯❯❯❯ rake db:migrate                                                                                                code/ahab_core master
rake aborted!
Don't know how to build task 'annotate_models'
/Users/dan/.rvm/gems/ruby-2.2.3/gems/annotate-2.6.7/lib/tasks/migrate.rake:29:in `update_annotations'
```

**Comment by djsegal** [comment]
---

#### Note: 

To get this to work in the parent repo and the engine/subtree repo, I also had to change the `auto_annotate_models.rake` that was within my subtree's lib.

---

This took two parts:

1 – namespacing set_annotation_options inside engine (I chose engine arbitrarily):

```
# in lib/subtree/lib/tasks/auto_annotate_models.rake:

namespace :engine do
  task :set_annotation_options do
    Annotate.set_defaults(
      ...
    )
  end
end
```

2 – adding an initializer to the engine to selectively undo namespacing:

```
    initializer :fix_migrations do |app|
      if app.root.to_s.match root.to_s
        task :set_annotation_options do
          Rake::Task["engine:set_annotation_options"].invoke
        end
      else
        ...
      end
    end
```

**Comment by djsegal** [comment]
--------------

^ The `...`'s in the else clause of the 2nd step of the previous comment ("adding an initializer to the engine") is related to another gotcha: bubbling database migrations up to the parent repo ([see this article](https://blog.pivotal.io/labs/labs/leave-your-migrations-in-your-rails-engines))

```
config.paths["db/migrate"].expanded.each do |expanded_path|
  app.config.paths["db/migrate"] << expanded_path
end
```

--------------

One last note to future readers about the database bubbling,

there is a gotcha related to running `rake db:drop db:create db:migrate` that occurs between create and migrate if you don't separate it into two lines (i.e. `rake db:migrate` after other two commands). The fix for this is to add `db.rake` to the parent repo's lib directory with the following task:

```
Rake::Task["db:load_config"].enhance [:environment]
```

--------------

**Comment by ngelx** [comment]
hey @djsegal, I've implemented your solution

```
# auto_anonte_models.rake

if Rails.env.development?
  namespace :engine do
    task :set_annotation_options do
       Annotate.set_defaults({
        .....
      })
    end
    Annotate.load_tasks
  end
end
```

```
# lib/test_engine/engine.rb
    initializer :fix_migrations do |app|
      if app.root.to_s.match root.to_s
        task :set_annotation_options do
          Rake::Task["engine:set_annotation_options"].invoke
        end
      else
        config.paths["db/migrate"].expanded.each do |expanded_path|
          app.config.paths["db/migrate"] << expanded_path
        end
      end
    end
```

But when i run `rake db:migrate` from the engine, no annotation is done. When i try to run `annotate` from the command line i get 

`Don't know how to build task 'engine:set_annotation_options' (RuntimeError)`

Any help would be much appreciated.
Thanks

**Comment by ctran** [comment]
Is this already fixed per #296

**Comment by Fornacula** [comment]
Still seems to be an issue in version 3.0.3

**Comment by blackbiron** [comment]
> Still seems to be an issue in version 3.0.3

as well as 3.1.1
