### ISSUE TITLE
Unable to annotate files associated with model when model is not directly in codebase

### ISSUE THREAD

**Issue by djsegal** [ctran/annotate_models#300]
For example, 
- if you have an engine gem that contains all your models and a wrapper rails api app that maintains the schema
- a `spec/models/user_spec.rb` file in the wrapper app should get annotated by the `models/user.rb` file in the separate gem

**Comment by ctran** [comment]
I'm not sure why you want to annotate a spec file associated with a engine.  I would consider everything inside an engine like a third-party library.

**Comment by djsegal** [comment]
It would be useful for an engine that carries models. You could then have a users_controller route in say: admin, api, etc and have them all get annotated.

I'll try to put together a PR soon

**Comment by aleksandrs-ledovskis** [comment]
Sad to see this closed without resolution. @ctran Are you willing to consider this change as community provided PR

**Comment by ctran** [comment]
Yes, I will accept any PR that is useful for the community and does not cause incompatibility.  Just dont have bandwidth on new features.
