### ISSUE TITLE
Postgres jsonb field defaults not annotating

### ISSUE THREAD

**Issue by chuck-john** [ctran/annotate_models#305]
Running annotations on a `jsonb` field in a `postgres` database does not notate default values.

**Comment by ctran** [comment]
Are you saying it used to do it or it never does?

**Comment by chuck-john** [comment]
It used to.  Version `2.6.10` annotated our project's `jsonb` fields' default values.  The latest release, `2.7.0`, removed those annotations.  I don't see an option to toggle default model values in the `auto_annotate` rake task.

**Comment by ctran** [comment]
I'm not sure what would have caused this.  Could you provide me with a sample model + migration file to reproduce tihs?

**Comment by chuck-john** [comment]
[Model](https://gist.github.com/chuck-john/dfc20389251b9331e380) and [Migration](https://gist.github.com/chuck-john/e1aca90d3feb60b42d43)

Rails 4.2.5
Postgres 9.4.5

**Comment by ctran** [comment]
This is actually submitted by #250.  I don't recall the reason behind this change though.
