### ISSUE TITLE
annotate -r annotates more than just route.rb

### ISSUE THREAD

**Issue by rhuppert** [ctran/annotate_models#306]
I recently updated to 2.7.0 and upon running annotate -r, I was surprised when helpers and controllers no included annotations.  I suspected the auto_annotate_models rake file was to blame, but even after marking unwanted default annotations false, it made no difference.  A message saying models and routes have not changed, but controllers and their spec files and helpers had been modified.

Running Rails 4.2.5, Ruby 2.2.3

**Comment by ctran** [comment]
This is due to #299.  Is it just a surprise or you don't find this useful?

**Comment by rhuppert** [comment]
It certainly was a surprise, since the readme indicates the -r argument annotates routes.rb with the output of 'rake routes.'  My assumption would be only the route file would be affected.

I should point out that the default behavior cannot be changed with respect to these new annotations' position in the file.  I prefer after my code, not before.

I can only speak for myself, but my preference would be to explicitly create that output and not have it happen automatically.  Perhaps being able to change the default behavior would be acceptable, but for me I do not find this particularly useful.

Happy New Year.

**Comment by ctran** [comment]
These are no longer annotated by default (develop branch).

**Comment by rhuppert** [comment]
Thanks, Cuong.  I appreciate the work you do.
