### ISSUE TITLE
Returning error if model not found

### ISSUE THREAD

**Issue by celsoMartins** [ctran/annotate_models#307]
The scenario: I have a migration to exclude a model, but this model can't be excluded until the migration execution in production.

This is the migration: https://github.com/agile-alliance-brazil/event_registrations/blob/master/db/migrate/20151231024432_drop_table_registration_price.rb

As you can see, it is a refactoring where we need some data.

So, I don't have the table, but I still have the model and the gem returns this error, cluttering the automatic build.

`Unable to annotate app/models/registration_price.rb: Mysql2::Error: Table 'agilebrazil_development.registration_prices' doesn't exist: SHOW CREATE TABLE `registration_prices`
Model files unchanged.`

**Comment by celsoMartins** [comment]
This commit deals with it?

https://github.com/ctran/annotate_models/commit/a1cc2a0f4d3ba948af921d01f2e15f530ba33122

**Comment by ctran** [comment]
Can you reproduce this with a stack trace?  ("bundle exec annotate --trace")

**Comment by ctran** [comment]
There is a guard to check if the table exists.  I can't seem to reproduce this scenario so you will have to give a step-by-step to reproduce this.
