### ISSUE TITLE
No way to turn off controller test annotations

### ISSUE THREAD

**Issue by chuck-john** [ctran/annotate_models#308]
There is no option to turn off controller test annotations.  The `exclude_controllers` and `exclude_tests` options do not seem to affect `ActionController::TestCase` files located in `test/controllers` or its subdirectories.

Rails 4.2.5
Annotate 2.7.0

**Comment by nchaffee** [comment]
Having the same problem!

**Comment by arturoherrero** [comment]
:+1: I like to keep the same behaviour that we had before.

**Comment by joker-777** [comment]
:+1:

**Comment by hut8** [comment]
:+1:

**Comment by ctran** [comment]
Have you tried to use the "exclude_scaffolds" option?

**Comment by ctran** [comment]
These are no longer annotated by default (develop branch).
