### ISSUE TITLE
Question: CI Support

### ISSUE THREAD

**Issue by DamirSvrtan** [ctran/annotate_models#317]
We often forget to roll annotations. Is there a way to let annotate_models check if everything is annotated  and if that isn't true, throw an abort so our CI build fails.

Thnx upfront.

**Comment by ctran** [comment]
I don't think there's currently possible.  It may require some tweaks to support.  

I never thought this gem would be part of a CI step though :-)

**Comment by ctran** [comment]
PR is welcome but I'm closing this.

**Comment by yokomotod** [comment]
+1 for this motivation and tried to submit PR #603 

very often I met changing annotations just after pull master and run migrate
because someone (sometimes, myself 😝) forgot to commit annotations...
I really want to detect it on CI.
