### ISSUE TITLE
position_in_test is ignored

### ISSUE THREAD

**Issue by buren** [ctran/annotate_models#321]
First of all thank you for an awesome gem :star:

I've set `position_in_test` to `"after"` and its ignored and is always added `before`. I manually moved the annotations to the bottom and tried to re-run `annotate --force` afterwards and all annotations where removed from the bottom and added to the top.

My env:
- annotate 2.7.0
- Rails 4.2.5
- Rspec 3.4

Thanks again for a great gem :)

**Comment by ctran** [comment]
It looks like the position_in_test  option is not even used anywhere :(

**Comment by buren** [comment]
Isn't it used on [annotate_models.rb#L447](https://github.com/ctran/annotate_models/blob/5177edd4fed542f699fe7eafe62f92eac7a12414/lib/annotate/annotate_models.rb#L447)? It is in [`MATCHED_TYPES`](https://github.com/ctran/annotate_models/blob/5177edd4fed542f699fe7eafe62f92eac7a12414/lib/annotate/annotate_models.rb#L12).

**Comment by netuoso** [comment]
Try changing "after" to 'after'.

If you rerun `rails g annotate:install` you will probably see all double quotes removed in favor for single quotes. As well as a new option or two in the config.

**Comment by jdugarte** [comment]
This isn't working yet. I have version 2.7.1.
