### ISSUE TITLE
Fix rubocop errors

### ISSUE THREAD

**Issue by ctran** [ctran/annotate_models#322]
It would be nice to fix up the code, see https://travis-ci.org/ctran/annotate_models/jobs/102820138.

**Comment by ryanfox1985** [comment]
I added rubocop config files and the test pases, with rubocop_todo.yml you'll fix the offenses when you have time.

You can merge to develop.

**Comment by ryanfox1985** [comment]
One moment I'll check this error.
Error: The `Style/TrailingComma` cop no longer exists. Please use `Style/TrailingCommaInLiteral` and/or `Style/TrailingCommaInArguments` instead.

**Comment by ctran** [comment]
Thanks to @ryanfox1985, this is now done in #324.
