### ISSUE TITLE
2.7.0: controller tests are annotaded despite 'exclude_tests' => "true"

### ISSUE THREAD

**Issue by bughit** [ctran/annotate_models#334]
other tests are not annotated

**Comment by bughit** [comment]
caused by exclude_scaffolds

**Comment by bughit** [comment]
one should not have to exclude a category twice (exclude_tests, exclude_scaffolds), exclude_tests should be sufficient for excluding tests

**Comment by ctran** [comment]
This is still an issue for 2.7.2?
