### ISSUE TITLE
Annotate runs before migrations when using Annotate.load_tasks

### ISSUE THREAD

**Issue by dkowsley** [ctran/annotate_models#338]
The way the migration hooks are implemented appears to cause the annotations to run before the migrations. You can run migrate twice and achieve the correct results, however this can be very obnoxious for environments where you are constantly rebuilding development databases and having several hundred file changes in git because of it.

**Comment by FME-Daniel** [comment]
Perhaps consider switching to something like
```ruby
%i(migrate rollback).each do |cmd|
  Rake::Task["db:#{cmd}"].enhance  do
    # invoke annotate task
  end
end
```
