### ISSUE TITLE
Dose not annotate database info correctly when I do commands: 1 "rake db:drop" → 2 "rake db:create" → 3 "rake db:migrate"

### ISSUE THREAD

**Issue by iToshk** [ctran/annotate_models#341]
But, when I do "rake db:migrate" again after 3 commands, annotation worked. 
Maybe, annotation are made from only create info in database at first time?

**Comment by lasseebert** [comment]
I have the same issue. Both when running `rake db:drop && rake db:create && rake db:migrate` and `rake db:drop db:create db:migrate`.

It seems that annotate will change the annotation comment to an older version, but only for two models (the same changes to the same models every time).

After running another `rake db:migrate` it is fixed again.

**Comment by FME-Daniel** [comment]
This is already documented here: https://github.com/ctran/annotate_models/issues/338
