### ISSUE TITLE
classified sort has problems if no id is present

### ISSUE THREAD

**Issue by lnxbil** [ctran/annotate_models#348]
Hi,

I want to switch from ```annotate``` to ```annotate --classified-sort``` and I encounter the following problem:

```
Unable to annotate app/models/schema_migration.rb: undefined method `type' for nil:NilClass
```

It also happens to other models without an ID too and the file gets not annotated at all. Without ```--classified-sort``` it works as expected, but the columns are obviously not sorted.

**Comment by kfarst** [comment]
@lnxbil from the description of the `--classified-sort` flag, it will `Sort columns alphabetically, but first goes id, then the rest columns, then the timestamp columns and then the association columns` so sorting by the `id` is part of the feature. @ctran should the annotation still work with missing columns?

**Comment by lnxbil** [comment]
The thing is that I do not want to select my tables with id and without upfront to run different annotation parameters to each of them. I think a fallback to not sorting is still better than skipping entirely, isn't it?

**Comment by ctran** [comment]
I would think so; It should skip the id column if it doesn't exist.
