### ISSUE TITLE
annotate --models

### ISSUE THREAD

**Issue by bsgreenb** [ctran/annotate_models#349]
`annotate --exclude tests,fixtures,factories,serializers` is my most common command.  would be nice to have something simpler like `annotate --models`

**Comment by ctran** [comment]
You certainly can create a shell alias or just the auto.rake feature.

**Comment by bodrovis** [comment]
Actually, I'd love to have this too. Or introduce `--only` option.

**Comment by ivobenedito** [comment]
Yeah, think something like ```annotate models``` or ```annotate --only models``` could make sense?
