### ISSUE TITLE
error:Unable to annotate app/models/blog_post.rb: undefined method `supports_foreign_keys?'

### ISSUE THREAD

**Issue by dborovsky** [ctran/annotate_models#352]
ruby 2.0.0p247

Rails 3.2.22

mysql

I added gem 'annotate' after bundle install. gem was installed

Next step: rails g annotate:install

next step: run rake db:migrate

Display error:

Unable to annotate app/models/blog_post.rb: undefined method `supports_foreign_keys?' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x0000000346aae8>

Similarly for other models

What wrong? How solve this issue. Thank you.

**Comment by henrik** [comment]
I get the same after upgrading 2.6.10 -> 2.7.0, but for Postgres.

This is on Rails 4.1.14.2, Ruby 2.2.0.

```
…
Unable to annotate app/models/synonym.rb: undefined method `supports_foreign_keys?' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x007f4bd1f96e28>
Unable to annotate app/models/transport.rb: undefined method `supports_foreign_keys?' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x007f4bd1f96e28>
…
```

**Comment by sashabelozerov** [comment]
Fixed already with https://github.com/ctran/annotate_models/commit/18eb2d0b31b13d2f429eae088c779fb8b7d48908
You can use `develop` branch until new version is released.

**Comment by henrik** [comment]
Thank you, @sashabelozerov!
