### ISSUE TITLE
Custom Constraints

### ISSUE THREAD

**Issue by tyre** [ctran/annotate_models#355]
I have a model with a column that cannot be less than zero. So I add a constraint:

``` SQL
ALTER TABLE walruses ADD CONSTRAINT check_value_is_positive CHECK (tusks >= 0)
```

Could we add the ability to add those custom constraints to the model annotation? Something like:

```
# Constraints
#   check_value_is_positive                     (tusks >= 0)
```

This information is available in `information_schema.table_constraints` via:

``` SQL
select * from information_schema.table_constraints where "table_name"='walruses'
```

**Comment by ctran** [comment]
Does this available across databases (via Rails api)?

**Comment by Tuxii** [comment]
Bumping this, this would be a useful feature.
