### ISSUE TITLE
When annotate --routes get error 

### ISSUE THREAD

**Issue by Xosmond** [ctran/annotate_models#356]
I'm having this error when "annotate --routes":

/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/annotate-2.7.0/bin/annotate:194:in `<top (required)>': undefined method `include_models?' for Annotate:Module (NoMethodError)
Did you mean?  included_modules
	from /usr/local/var/rbenv/versions/2.3.0/bin/annotate:22:in `load'
	from /usr/local/var/rbenv/versions/2.3.0/bin/annotate:22:in `<main>'

**Comment by ctran** [comment]
I'm not able to reproduce this with the latest version.

**Comment by adesurirey** [comment]
Same issue with `annotate`@Xosmond did you find a solution ?

**Comment by adesurirey** [comment]
Fixed using `gem 'annotate', git: 'https://github.com/ctran/annotate_models.git'`
