### ISSUE TITLE
annotate --routes changes model files

### ISSUE THREAD

**Issue by aminariana** [ctran/annotate_models#357]
When I do a simple:
`annotate --routes`

I expect only the `routes.rb` file to change, not the model annotations. But they do.

My usage hasn't changed from previous versions of annotate. But going from `v2.6.10` to `v2.7`, when I run the command, it overrides my existing model annotations with fresh ones, without the desired options such as annotating indexes that I otherwise specify in annotating models. Breaking change I think?

EDIT:

Downgrading to v2.6.10 fixes the problem.

**Comment by kamilbielawski** [comment]
I believe the behaviour you described is like that by design.
I've just made a small PR with additional option (`--ignore-models`) that will let you achieve desired behaviour. However, I'm not entirely sure if that's the right approach. It would be great to hear @ctran's opinion

**Comment by aminariana** [comment]
If by design, why inconsistent between two versions?

If I annotate routes, it violates my expectations to see model files modified.

**Comment by Hitabis** [comment]
Why not annotating only the routes when calling `annotate --routes`?
It would only be necessary to check the presence of the `routes` argument and the user would get the expected result.
This is the function causing the unexpected behavior: https://github.com/ctran/annotate_models/blob/6775e4a16d853c3484f7753198220cbeb99bba8d/lib/annotate.rb#L116

**Comment by ctran** [comment]
Ah, I misread the existing behavior.

**Comment by javierguajardo** [comment]
@aminariana I've tested your issue using:
* Rails 5.2.0
* Ruby 2.5.1
* Annotate 2.7.3

I ran `annotate --routes` and only the `config/routes.rb` file was changed. I believe this problem has been patched with 2.7.3.

Regards.
