### ISSUE TITLE
Procs are badly annotated

### ISSUE THREAD

**Issue by pupeno** [ctran/annotate_models#369]
When you have a route with proc, such as:

``` ruby
match "/users/invitation", via: :all, to: proc { raise ActionController::RoutingError.new('Not Found') }
```

the route is annotated exposing local paths and with an id that may change:

``` ruby
#           users_invitation        /users/invitation(.:format)                             #<Proc:0x007ffa23247d98@/Users/pupeno/project_x/config/routes.rb:3>
```

It would be better to just <Proc> or something like that.

**Comment by b264** [comment]
I have seen the same thing.  Every run produces a git diff because the number changes.
```ruby
#   Prefix Verb   URI Pattern            Controller#Action
#                 /__OPAL_SOURCE_MAPS__  #<Opal::SourceMapServer:49235340>
```

Maybe `.class.name` should annotate if it's not a string?

**Comment by JoeWoodward** [comment]
+1 I'm experiencing this issue on every merge from another developer. It's becoming fairly annoying. Does anyone know the offending code so I can have a go at fixing it?

**Comment by b264** [comment]
It appears to be coming from Rails and not from annotate.
https://github.com/ctran/annotate_models/blob/develop/lib/annotate/annotate_routes.rb#L54

**Comment by b264** [comment]
possibly from here ?
https://github.com/rails/rails/blob/643cac08a325243cab21d870c68a9c4088c58380/actionpack/lib/action_dispatch/routing/inspector.rb#L8

**Comment by shockone** [comment]
A workaround:

```ruby
  invitation_endpoint = proc { raise ActionController::RoutingError.new('Not Found') }.tap do |proc|
    def proc.inspect
      'proc endpoint'
    end
  end

  match "/users/invitation", via: :all, to: invitation_endpoint
```
