### ISSUE TITLE
Support special comments at beginning of files.

### ISSUE THREAD

**Issue by jpickwell** [ctran/annotate_models#371]
Annotate only prepends to the beginning of a file, which means that any special comments that were before the annotation, end up after the annotation. A hook should be used to allow Annotate to replace an annotation inline when an annotation is present, but prepend when an annotation is not present.

This would allow for custom comments before and after the annotation.

**Comment by b264** [comment]
There are a few things it leaves alone https://github.com/ctran/annotate_models/blob/develop/spec/annotate/annotate_models_spec.rb#L688-L702

**Comment by jpickwell** [comment]
For routes, it removed the annotation and then added the new annotation above the special comments.
