### ISSUE TITLE
Annotate is annotating my controller!

### ISSUE THREAD

**Issue by MatthewRDodds** [ctran/annotate_models#373]
I've noticed that I have one controller that gets annotated, and I believe it's because it has 'Base' in the naming, at least that's the difference I've found from my other controllers:

app/controllers/tasks_controller.rb

``` ruby
class TasksController < BaseTaskController
  #...
end
```

When I remove the annotation comments at the top and run annotate with no arguments I see this output:

```
$ bin/annotate
Annotated (1): app/models/task.rb
```

**Comment by mihaibb** [comment]
It happens to me also when I run `bundle exec annotate` it shows `Annotated (6): app/models/client.rb, app/models/document.rb, ...` and it adds all the model annotations to controllers that seems to be scaffolds of the model.

**Comment by heaven** [comment]
And to specs. Why does it need more info? Do you have any troubles reproducing this?

**Comment by prusswan** [comment]
annotate_models.rb:15:
`MATCHED_TYPES = %w(test fixture factory serializer scaffold`

annotate_models.rb:105:
`scaffold_files`  include all the specs that are related to the inferred model (controllers, requests, routing) 
So all these specs will be annotated unless scaffolds are excluded (`:exclude_scaffolds => true`)
