### ISSUE TITLE
Controller annotations appear at the top no matter what

### ISSUE THREAD

**Issue by kt32291** [ctran/annotate_models#374]
No matter whether I configure the position of the annotations through options passed to the command, or in the options in the backend config, I cannot get the controller annotations to appear at the bottom of the file. Why is this happening?

**Comment by FME-Daniel** [comment]
I'm not sure what you mean about `passed to the command` but I am able to annotate controllers, during migration, with this loaded along with the rake tasks:
```ruby
if Rails.env.development? && Rake::Task.task_defined?('db:migrate')
  %i(migrate rollback).each do |cmd|
    Rake::Task["db:#{cmd}"].enhance do
      `annotate --sort -ikp after`
    end
  end
end
```
