### ISSUE TITLE
Excluding controllers should also exclude controller specs

### ISSUE THREAD

**Issue by johncarney** [ctran/annotate_models#375]
If I exclude controllers from annotation, `annotate` will still annotate my controller specs. It should not do this - if I don't want my controllers annotated, why would I want the corresponding specs annotated?

This thinking should also be applied to helpers and models.

**Comment by pupeno** [comment]
Same for controller tests. There seems to be no way to stop controller tests from being annotated at all.

**Comment by javvarcar** [comment]
+1

**Comment by PikachuEXE** [comment]
Still happens for 2.7.1
```
Annotate.version
=> "2.7.1"

Rails.version
=> "5.0.1"
```

**Comment by PikachuEXE** [comment]
Ignore my last comment, didn't know config need to be updated

**Comment by roberthead** [comment]
@PikachuEXE *How* does the config need to be updated?
