### ISSUE TITLE
"Custom" postgres database indexes not shown

### ISSUE THREAD

**Issue by micred** [ctran/annotate_models#380]
We have many case-insensitive indexes in postgresql (as in the second example of [pg documentation](https://www.postgresql.org/docs/9.1/static/sql-createindex.html#AEN66303)).

These index are not printed by annotate.

How to replicate: 

```
class AddNameIndexToFilm < ActiveRecord::Migration
  def change
    execute 'CREATE INDEX index_films_on_lower_title ON films ((lower(title)));'
end
```

**Comment by uberllama** [comment]
Funny, I was just about to post something similar, except in my case I want to see index types (btree, gin, etc).

**Comment by ctran** [comment]
Is this similar to #377?
