### ISSUE TITLE
Overriding method_missing breaks find_by matchers

### ISSUE THREAD

**Issue by amcaplan** [ctran/annotate_models#384]
The gem overrides method_missing on all `ActiveRecord` models here: https://github.com/ctran/annotate_models/blob/65af43e622b6257422ead1a8ec8c0957ff0b95fd/lib/annotate/active_record_patch.rb#L5

This causes all dynamically generated `find_by_whatever` methods to stop working because those rely on method_missing.

True, they're deprecated at this point, but plenty of apps will be using these methods for years (especially since the Rails team has made them available as a gem: https://github.com/rails/activerecord-deprecated_finders so you know tons of apps will just re-add them in).

Maybe we could let methods that start with `find_by_` through?

**Comment by amcaplan** [comment]
As another suggestion, and to better maintain forward compatibility, maybe instead of overriding `method_missing`, add a module with the same method.  Something like:

``` ruby
module MethodMessingDefaultsToNil
    def self.method_missing(_name, *_args)
      # ignore this, so unknown/unloaded macros won't cause parsing to fail
      super rescue nil
    end
end

ActiveRecord::Base.prepend(MethodMissingDefaultsToNil)
```
That method_missing will catch any calls to `super` that fail after `ActiveRecord::Base` deals with it via default behavior.  Obviously may want to be judicious about what it rescues.

Here's a trivial example of this kind of prepending behavior:

``` ruby
class Foo
  def method_missing(meth, *args, &block)
    if meth == :hey
      4
    else
      super
    end
  end
end

Foo.new.hey
=> 4
Foo.new.what
NoMethodError: undefined method `what' for #<Foo:0x007ff411862150>
  from (irb):6:in `method_missing'
  from (irb):11
  from /Users/acaplan/.rvm/rubies/ruby-2.2.4/bin/irb:11:in `<main>'

module Bar
  def method_missing(meth, *args, &block)
    super rescue 'rescued from module'
  end
end

Foo.prepend(Bar)

Foo.new.hey
=> 4
Foo.new.what
=> "rescued from module"
```

**Comment by ctran** [comment]
Sound suggestion.  I'll try to put together a PR this weekend unless someone else beats to me to it.

**Comment by ctran** [comment]
This seems to be bit tricker than I thought.
