### ISSUE TITLE
Not recording JSONB defaults in 2.7.1 (but worked in 2.6.10)

### ISSUE THREAD

**Issue by nneal** [ctran/annotate_models#387]
We upgrade from 2.6.10 to 2.7.1 and are experiencing the following problem, across many different tables where we have JSONB fields

old annotation (v 2.6.10)
```
#  data_fields       :jsonb            default({}), not null
```

new annotation (v 2.7.1)
```
#  data_fields       :jsonb            not null
```

the corresponding line in schema.rb
```
t.jsonb    "data_fields",       default: {}, null: false 
```

--------------------

Another problem is, for some reason, one single controller spec is now being annotated, though other controllers aren't:

```spec/controllers/invite_codes_controller_spec.rb  ``` gets annotated but the rest of our controller specs are left around. and we have ``` 'exclude_tests'        => "true", ``` set in the rake setting file ... which we had before and worked fine in previous version

Thanks!

**Comment by vietqhoang** [comment]
Just want to comment I am seeing the same issue where default isn't being listed for both jsonb and json data types. I am using Rails 5.0.0 and annotate_models 2.7.1

**Comment by nneal** [comment]
to add to this, we're on rails 4.2.latest

**Comment by jastkand** [comment]
The problem is that `json`,`jsonb` and `hstore` column types were added to a list of types for which default is not shown. This PR https://github.com/ctran/annotate_models/pull/389 makes this behavior optional.

**Comment by ctran** [comment]
The default value for jsonb is no longer displayed since it may break formatting.  If you use the github version, you can now enable it with #389.
