### ISSUE TITLE
Support line length for comments.

### ISSUE THREAD

**Issue by aaronmallen** [ctran/annotate_models#394]
I would like to see support for line length on annotation comments.  Where it would automatically carry over comments that are over the specified line length to the next line.  This would be super beneficial in ensuring models meet rubocop compliance for a given project rule set.

**Comment by aaronmallen** [comment]
bonus points if it actually looks at the rules defined by `.rubocop.yml`

**Comment by binarymason** [comment]
+1

**Comment by leonelgalan** [comment]
If you are using markdown output, _annotate_ outputs a table which is hard or impossible to break the line. Most of us simply add wrappers to the annotation to disable that check:

```ruby
Annotate.set_defaults wrapper_open: 'rubocop:disable Metrics/LineLength',
                      wrapper_close: 'rubocop:enable Metrics/LineLength'
```

**Comment by aaronmallen** [comment]
That's what I did to address the issue but it felt somewhat hacky to do so.

**Comment by aaronmallen** [comment]
@leonelgalan in addition to it being hacky you can also run into trouble with the Lint/UnneededDisable cop

**Comment by leonelgalan** [comment]
I don't see it as hacky, when I want markdown tables. It would be too hard for this library to break the lines without messing it up. I know I can't have short lines, verbose (markdown) tables and optional wrappers.

One way we could all get what we want is if there was a way to customize the comment before it's written into the model:

```ruby
# Default:
Proc.new { |schema_comment| schema_comment }

# Smarter Wrappers
Proc.new do |schema_comment|
  too_long = schema_comment.split("\n").any? { |line| line.length > 80 }
  if too_long
    [
      'rubocop:disable Metrics/LineLength',
      schema_comment,
      'rubocop:enable Metrics/LineLength'
    ].join("\n")
  else
    schema_comment
  end
end
```

Even breaking longer lines should be possible and the responsibility would move away from annotate into the user.

**Comment by betesh** [comment]
:+1:

**Comment by mull** [comment]
Any progress on this? :)
