### ISSUE TITLE
Wrapper is not applied to route annotation

### ISSUE THREAD

**Issue by NuckChorris** [ctran/annotate_models#401]
I have a wrapper to disable line length checks in Rubocop, but it's not applied to route annotations.

**Comment by leonelgalan** [comment]
Could you show us your configuration? How did you added the wrapper? Please include all pertinent information to make it easier for others to help you.

I have a similar wrapper and it works fine:

```ruby
Annotate.set_defaults wrapper_open: 'rubocop:disable Metrics/LineLength',
                      wrapper_close: 'rubocop:enable Metrics/LineLength'
```

**Comment by viamin** [comment]
I'm seeing this also, using the automatic rake task. 

It looks like annotate_routes.rake doesn't load the wrapper_open or wrapper_close options:

    desc "Adds the route map to routes.rb"
    task :annotate_routes => :environment do
      annotate_lib = File.expand_path(File.dirname(File.dirname(__FILE__)))
      require "#{annotate_lib}/annotate/annotate_routes"
      options={}
      ENV['position'] = options[:position] = Annotate.fallback(ENV['position'], 'before')
      options[:position_in_routes] = Annotate.fallback(ENV['position_in_routes'], ENV['position'])
      options[:ignore_routes] = Annotate.fallback(ENV['ignore_routes'],  nil)
      options[:require] = ENV['require'] ? ENV['require'].split(',') : []
      AnnotateRoutes.do_annotations(options)
    end

Also, annotate_routes.rb doesn't appear to look for the wrapper options.

**Comment by betesh** [comment]
:+1:

**Comment by betesh** [comment]
I just tried this with commit e763429ebe1d02c2d4a4a3a0dc3d4eeb58c12100, and it puts the route annotations above the magic comments.

**Comment by ctran** [comment]
Could you provide any useful info for @sashabelozerov to track it down?

**Comment by sashabelozerov** [comment]
I see. Currently `AnnotateRoutes` module have no idea about magic comments at all. I'll try to add this soon.
