### ISSUE TITLE
Do not include auto-generated foreign key names in schema dump

### ISSUE THREAD

**Issue by vergenzt** [ctran/annotate_models#404]
My app uses Rails' [autogenerated random foreign key names](https://github.com/rails/rails/commit/8768305f20d12c40241396092a63e0d56269fefe).

## Problem
I frequently drop my dev database, regenerate it from migrations, and reseed it. Every time I do this, the foreign key names change, and `annotate_models` includes the changed names in its annotations.

ActiveRecord's SchemaDumper avoids this by [not dumping the name iff it matches the regex `/^fk_rails_[0-9a-f]{10}$/`](https://github.com/rails/rails/commit/8768305f20d12c40241396092a63e0d56269fefe#diff-e0d63791fb8e00fc467e7c47b74fb6d6R239):

```rb
if foreign_key.name !~ /^fk_rails_[0-9a-f]{10}$/
  parts << ('name: ' + foreign_key.name.inspect)
end
```

## Proposal

Would you be open to accepting a PR that adds a similar check to `annotate_models`?

### Considerations
I'm not sure how the formatting would work.

**Example (right now)**:
```rb
# Foreign Keys
#
#  fk_rails_3a1015a040  (user_id => users.id)
#  fk_rails_8941ddb7a6  (application_id => applications.id)
```

**Option 1** (proposal):
```rb
# Foreign Keys (random names elided)
#
#  fk_rails_XXXXXXXXXX  (user_id => users.id)
#  fk_rails_XXXXXXXXXX  (application_id => applications.id)
```

**Comment by ctran** [comment]
This sounds like a reasonable change.  a PR would definitely be welcome.

**Comment by vergenzt** [comment]
Do you like the proposed replacement format? I'm not sure I do, but I don't know what would be better. :/

**Comment by vergenzt** [comment]
Also should I include an option to retain previous behavior or not bother?

**Comment by ctran** [comment]
I like what you proposed.  I think there isn't much value in retaining the old behavior where the names are changing every time you run.

**Comment by vergenzt** [comment]
What about this? I think I like it better, personally.

```rb
# Foreign Keys (auto-generated names elided)
#
#  (foreign_thing_id => foreign_things.id)
#  (different_thing_id => different_things.id)
#
```

Then if there's a mixture of manually-set and auto-generated names, it'll look like:
```rb
# Foreign Keys (auto-generated names elided)
#
#                     (foreign_thing_id => foreign_things.id)
#  my_custom_fk_name  (different_thing_id => different_things.id)
#
```

**Comment by vergenzt** [comment]
Or, to make it look prettier in the likely-more-common case that there are no foreign key names:

**Option 3**:

```rb
# Foreign Keys (auto-generated names elided)
#
#  foreign_thing_id => foreign_things.id
#  different_thing_id => different_things.id
#
```

Then if there's a mixture of manually-set and auto-generated names, it'd look like:
```rb
# Foreign Keys (auto-generated names elided)
#
#                      foreign_thing_id => foreign_things.id
#  my_custom_fk_name:  different_thing_id => different_things.id
#

---

I think Option 3 is my favorite. :)

(Sorry for the spam!)

**Comment by ctran** [comment]
We should try to retain the existing format unless there's a really good reason to do so.  In this case, I would be against changing the format for normal foreign keys.  For the generated fkeys, they should match existing format for the same reason.  I think consistency is important.  

Personally, I like the first proposal since it uses the existing format and it's clear that the names are not actual names:

fk_foo        (foo_id => users.id)
fk_bar        (bar_id => applications.id)
fk_rails_...  (application_id => applications.id)
fk_rails_...  (other_id => applications.id)

**Comment by vergenzt** [comment]
Opened PR at #408! Let me know what you think.
