### ISSUE TITLE
release v2.7.2 ?

### ISSUE THREAD

**Issue by mathieujobin** [ctran/annotate_models#407]

**Comment by vergenzt** [comment]
+1

**Comment by ryanfox1985** [comment]
+1

**Comment by ryanfox1985** [comment]
https://media.giphy.com/media/o5oLImoQgGsKY/giphy.gif

**Comment by ryanfox1985** [comment]
<img src="https://media.giphy.com/media/o5oLImoQgGsKY/giphy.gif" />

**Comment by carlodallamico** [comment]
+1

**Comment by tataata** [comment]
+

**Comment by vincentwoo** [comment]
2.7.2 would be great to silence Fixnum deprecation warnings!

**Comment by codebycliff** [comment]
Any chance at a release soon? I'm hoping to silence the `::Fixnum`/`::Bignum` deprecations without pointing my gemfile to master.

**Comment by ctran** [comment]
This weekend, promise :-)

**Comment by ctran** [comment]
I have trouble installing json with ruby 2.4 which stops me from releasing this.  Is this a known issue?

**Comment by vincentwoo** [comment]
Can you post your error? Might be able to help.

**Comment by ctran** [comment]
$ gem install json
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /Users/cuong.tran/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-2.0.3/ext/json/ext/generator
/Users/cuong.tran/.rbenv/versions/2.4.0/bin/ruby -r ./siteconf20170322-64992-m5ed9p.rb extconf.rb
creating Makefile

current directory: /Users/cuong.tran/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-2.0.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/cuong.tran/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-2.0.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c:337:5: warning: expression result unused [-Wunused-value]
    GENERATE_JSON(object);
    ^~~~~~~~~~~~~~~~~~~~~
./generator.h:92:5: note: expanded from macro 'GENERATE_JSON'
    rb_scan_args(argc, argv, "01", &Vstate);                                                    \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cuong.tran/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2142:5: note: expanded from macro 'rb_scan_args'
    __builtin_choose_expr(__builtin_constant_p(fmt), \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:349:5: warning: expression result unused [-Wunused-value]
    GENERATE_JSON(array);
    ^~~~~~~~~~~~~~~~~~~~
./generator.h:92:5: note: expanded from macro 'GENERATE_JSON'
    rb_scan_args(argc, argv, "01", &Vstate);                                                    \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cuong.tran/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2142:5: note: expanded from macro 'rb_scan_args'
    __builtin_choose_expr(__builtin_constant_p(fmt), \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:360:5: warning: expression result unused [-Wunused-value]
    GENERATE_JSON(integer);
    ^~~~~~~~~~~~~~~~~~~~~~
./generator.h:92:5: note: expanded from macro 'GENERATE_JSON'
    rb_scan_args(argc, argv, "01", &Vstate);                                                    \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cuong.tran/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2142:5: note: expanded from macro 'rb_scan_args'
    __builtin_choose_expr(__builtin_constant_p(fmt), \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:392:5: warning: expression result unused [-Wunused-value]
    GENERATE_JSON(float);
    ^~~~~~~~~~~~~~~~~~~~
./generator.h:92:5: note: expanded from macro 'GENERATE_JSON'
    rb_scan_args(argc, argv, "01", &Vstate);                                                    \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cuong.tran/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2142:5: note: expanded from macro 'rb_scan_args'
    __builtin_choose_expr(__builtin_constant_p(fmt), \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:414:5: warning: expression result unused [-Wunused-value]
    GENERATE_JSON(string);
    ^~~~~~~~~~~~~~~~~~~~~
./generator.h:92:5: note: expanded from macro 'GENERATE_JSON'
    rb_scan_args(argc, argv, "01", &Vstate);                                                    \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cuong.tran/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2142:5: note: expanded from macro 'rb_scan_args'
    __builtin_choose_expr(__builtin_constant_p(fmt), \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:469:5: warning: expression result unused [-Wunused-value]
    GENERATE_JSON(true);
    ^~~~~~~~~~~~~~~~~~~
./generator.h:92:5: note: expanded from macro 'GENERATE_JSON'
    rb_scan_args(argc, argv, "01", &Vstate);                                                    \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cuong.tran/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2142:5: note: expanded from macro 'rb_scan_args'
    __builtin_choose_expr(__builtin_constant_p(fmt), \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:479:5: warning: expression result unused [-Wunused-value]
    GENERATE_JSON(false);
    ^~~~~~~~~~~~~~~~~~~~
./generator.h:92:5: note: expanded from macro 'GENERATE_JSON'
    rb_scan_args(argc, argv, "01", &Vstate);                                                    \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cuong.tran/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2142:5: note: expanded from macro 'rb_scan_args'
    __builtin_choose_expr(__builtin_constant_p(fmt), \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:489:5: warning: expression result unused [-Wunused-value]
    GENERATE_JSON(null);
    ^~~~~~~~~~~~~~~~~~~
./generator.h:92:5: note: expanded from macro 'GENERATE_JSON'
    rb_scan_args(argc, argv, "01", &Vstate);                                                    \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cuong.tran/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2142:5: note: expanded from macro 'rb_scan_args'
    __builtin_choose_expr(__builtin_constant_p(fmt), \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:503:5: warning: expression result unused [-Wunused-value]
    rb_scan_args(argc, argv, "01", &state);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cuong.tran/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2142:5: note: expanded from macro 'rb_scan_args'
    __builtin_choose_expr(__builtin_constant_p(fmt), \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:982:5: warning: expression result unused [-Wunused-value]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cuong.tran/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2142:5: note: expanded from macro 'rb_scan_args'
    __builtin_choose_expr(__builtin_constant_p(fmt), \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10 warnings generated.
linking shared-object json/ext/generator.bundle
ld: symbol dyld_stub_binding_helper not found, normally in crt1.o/dylib1.o/bundle1.o for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [generator.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/cuong.tran/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-2.0.3 for inspection.
Results logged to /Users/cuong.tran/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-15/2.4.0-static/json-2.0.3/gem_make.out

**Comment by b264** [comment]
Is it related to https://twitter.com/miishke/status/527813954282979328

**Comment by vincentwoo** [comment]
Yeah, definitely sounds like your build environment is borked in some way. I don't think there's a problem with `json` installation currently.

**Comment by ctran** [comment]
That's what I suspect.  Will have to dig my way out of this mess.

Thanks.

**Comment by IgorPetkovic** [comment]
@ctran Any update on this ? Still the same error or ?

**Comment by aldesantis** [comment]
@ctran +1 We could really use this 😢

**Comment by steveklebanoff** [comment]
![waiting](https://media.giphy.com/media/tXL4FHPSnVJ0A/giphy.gif)

**Comment by steveklebanoff** [comment]
Sorry for the snarky gif, didn't realize 2.7.2 was released the day before but this issue hadn't been closed yet 

![embarrassed](https://media.giphy.com/media/rpf0Du8NasK6Q/giphy.gif)

**Comment by ctran** [comment]
@steveklebanoff It's no problem.  I do enjoy the occasionally giphy.
