### ISSUE TITLE
Error for model in subdirectory

### ISSUE THREAD

**Issue by axhamre** [ctran/annotate_models#413]
I'm on Rails 5.0.

Annotate has worked fine for me until I put my models in different subdirectories under the directory 'models'.

Now I get the following notive (which is incorrect) for two of my models (i.e. not all) when running `annotate -p bottom`:

    Unable to annotate app/models/physical/meeting_link.rb: You tried to define an enum named "availability" on the model "MeetingLink", but this will generate a instance method "default_availability?", which is already defined by another enum.

**Comment by Tybot204** [comment]
This happens to me as well on Rails 4.2.7. All of my enum attributes give a similar set of errors when the model is placed inside of a sub directory. This error prevents the model from being annotated, and is not just a warning message.
```
Unable to annotate app/models/tms/fee.rb: You tried to define an enum named "fee_type" on the model "Fee", but this will generate a instance method "fee_type=", which is already defined by another enum.
```

**Comment by davidlbean** [comment]
+1

**Comment by davidlbean** [comment]
@hundsim @Tybot204 - so I was having the same problem and I dug into things to see if I could produce a solution...  I found that the error we're all getting is from ActiveRecord itself when Annotate loads the model file.  In my case, it was because I had defined a model in a subdirectory without adding a matching namespace via a module.  Specifically:  
'''
I have a directory structure like this:
-- app
 -- models
   -- my_class_a.rb
   -- my_class_b.rb
   -- summary_review
       -- my_nested_class_with_enum.rb
       -- my_nested_class_without_enum.rb
'''

Initially, my_nested_class_with_enum.rb defined:
'''
   class MyNestedClassWithEnum
     ...
   end       
'''

But, once I defined it with a namespace like this:
'''
   module SummaryReview
      class MyNestedClassWithEnum
         ...
       end
   end
'''
everything worked fine. 

Hope that helps.

- David

**Comment by Tybot204** [comment]
@davidlbean Ah yes that looks like it might be my problem as well.
My directory structure:
```
-- app
 -- models
   -- my_class_a.rb
   -- my_class_b.rb
   -- directory_in_models
       -- my_nested_class_with_enum.rb
       -- my_nested_class_without_enum.rb
```
I was then auto loading these models so Rails treated them the same as if they were not nested:
```ruby
## Inside application.rb
config.autoload_paths += Dir[Rails.root.join('app', 'models', 'directory_in_models', '**/')]
```

I'll do some testing with this shortly. It would be nice to find a solution for not using a module though! I have many classes already in folders being autoloaded, and it would take some time to refactor all instances where I call these models.

**Comment by manuelmeurer** [comment]
Is there any solution to this? I also have many models in subfolders without a corresponding namespace, and I load them using `config.autoload_paths += Dir[Rails.root.join('app', 'models', '{*/}')]` and everything works fine, except that they cannot be annotated if they contain an `enum`. Seems like a bug in this gem.
@ctran What can I do to help debug this?

**Comment by ctran** [comment]
@manuelmeurer Can you add a sample (see spec/integration for an example) to that illustrates your problem?

**Comment by manuelmeurer** [comment]
Is this fixed?

**Comment by ctran** [comment]
Hi @manuelmeurer,
I'm closing out old issues without any activity.  If you still have a problem, please open a new issue with more relevant information.

**Comment by manuelmeurer** [comment]
Just tried it again, seems work fine! 👍
