### ISSUE TITLE
[Feature request] Support database comments

### ISSUE THREAD

**Issue by okuramasafumi** [ctran/annotate_models#433]
Rails 5 supports comments in database. It would be convenient if they appear in annotations.

**Comment by deepj** [comment]
Rails 5 supporting adding comments in migrations

http://blog.bigbinary.com/2016/06/21/rails-5-supports-adding-comments-migrations.html

**Comment by hemju** [comment]
This would be a great feature. Anything we can help you to implement it?

**Comment by gambala** [comment]
PR was merged, but feature didn't work for me :(

Ruby 2.4.1, Rails and ActiveRecord 5.1.1, annotate 2.7.2.

Used both `annotate` and `rake annotate_models`. Rake task was generated by `annotate:install` with this option in generated file:

```
'with_comment'              => true
```

**Comment by okuramasafumi** [comment]
Thank you for your work @motot and @dslh!
It seems the final working version is not released yet, so I cannot close this issue.
I'm waiting for the new release, @ctran!

**Comment by Adeynack** [comment]
@ctran : You closed the issue on Feb. 14th. However, the last release I see on GH dates 2018. Is this feature here bundled in this last release (2.7.4) or not yet? If not yet, when will it be? My team wants to use that feature.
