### ISSUE TITLE
Rake 12.0.0 Support

### ISSUE THREAD

**Issue by looorent** [ctran/annotate_models#435]
Do you plan to support rake 12.0.0 in the next release?
Best regards

**Comment by andyklimczak** [comment]
the `develop` branch supports 12.0.0 (specifically `rake (>= 10.4, < 12.1)`)

`gem 'annotate', git: 'https://github.com/ctran/annotate_models.git', branch: 'develop'`

**Comment by looorent** [comment]
Awesome. Thank you!
