### ISSUE TITLE
v2.7.1 uses Fixnum / Bignum deprecated by Ruby 2.4.0

### ISSUE THREAD

**Issue by brigneld** [ctran/annotate_models#439]
Using v2.7.1 with Ruby 2.4.0 results in the following:
`/home/damien/.rvm/gems/ruby-2.4.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:169: warning: constant ::Fixnum is deprecated
/home/damien/.rvm/gems/ruby-2.4.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:169: warning: constant ::Bignum is deprecated`

**Comment by b264** [comment]
I think this was fixed in https://github.com/ctran/annotate_models/pull/415 and just needs a new release minted

**Comment by allaire** [comment]
@b264 Running on master and still getting this warning

**Comment by allaire** [comment]
And getting

`Expected string default value for '--serializer'; got true (boolean)`

As well

**Comment by b264** [comment]
@allaire it was fixed in `develop` instead of `master`

**Comment by b264** [comment]
```gem 'annotate', git: 'https://github.com/ctran/annotate_models.git', branch: 'develop'```

**Comment by ctran** [comment]
Duped of #415.
