### ISSUE TITLE
Default string option for integer

### ISSUE THREAD

**Issue by 14113** [ctran/annotate_models#440]
Annotation on model shows default("STRING") but type is integer.

From DB
```
    Column    |            Type             | Description 
--------------+-----------------------------+--------------------
 id           | integer                     | not null
 sync         | smallint                    | default 0  
```

From model
```
# Table name: XXX
#
#  id           :integer          not null, primary key
#  sync         :integer          default("unsynchronized")

enum sync: { unsynchronized: 0, running: 1, synchronized: 2 }
```

You can see default("**unsynchronized**")
It's confusing, and for a moment I was worried that application store string instead of integer.

Please let me know your opinion, should I fix it, or it's 'feature'? :)

**Comment by b264** [comment]
`default("unsynchronized" as 0)` might be more clear, in my opinion
