### ISSUE TITLE
Why rake < 12.1

### ISSUE THREAD

**Issue by sjain** [ctran/annotate_models#443]
Can we update rake to latest?

https://github.com/ctran/annotate_models/blob/develop/annotate.gemspec#L29

**Comment by ctran** [comment]
Because that was the latest version at the time?

**Comment by dankimio** [comment]
@ctran The rake requirement `(< 12.0)` in version `2.1.7` conflicts with the installed latest version of rake `12.0.0`. Because of this we need to run commands via `bundle exec` for almost every Rails task. Is the upper boundary really necessary here? I think we could just drop it.

**Comment by sjain** [comment]
^ Exactly. Why not drop the upper limit?
