### ISSUE TITLE
annotate 2.7.1 breaking with Rails/ActiveSupport 5.0.1

### ISSUE THREAD

**Issue by diego-** [ctran/annotate_models#444]
On ruby 2.4.0, getting the following error:

`/Users/.../.rvm/gems/ruby-2.4.0/gems/annotate-2.7.1/lib/annotate.rb:12:in 'require': cannot load such file -- active_support/core_ext/hash/indifferent_access (LoadError)`

**Comment by Marthyn** [comment]
👍

**Comment by diego-** [comment]
note: this only occurs in standalone execution mode; when installed via Gemfile and executed with bundle exec, it works properly.

**Comment by LeKristapino** [comment]
Might be because there is no runtime dependency on `active_support`, only on `active_record`. So in Rails context it works fine, but without any context it fails.

**Comment by fa-cruzfernandez** [comment]
I'm getting a pretty similar error on my rails 3 app (with 2.7.1, 2.6.5 and 2.6.3) when I ran annotate command:
```
/MYMACHOME/.rbenv/versions/2.3.0/gemsets/my_project_in_rails_3/gems/annotate-2.7.1/lib/annotate.rb:12:in `require': cannot load such file -- active_support/core_ext/hash/indifferent_access (LoadError)
	from /MYMACHOME/.rbenv/versions/2.3.0/gemsets/my_project_in_rails_3/gems/annotate-2.7.1/lib/annotate.rb:12:in `rescue in <top (required)>'
	from /MYMACHOME/.rbenv/versions/2.3.0/gemsets/my_project_in_rails_3/gems/annotate-2.7.1/lib/annotate.rb:6:in `<top (required)>'
	from /MYMACHOME/.rbenv/versions/2.3.0/gemsets/my_project_in_rails_3/gems/annotate-2.7.1/bin/annotate:18:in `require'
	from /MYMACHOME/.rbenv/versions/2.3.0/gemsets/my_project_in_rails_3/gems/annotate-2.7.1/bin/annotate:18:in `<top (required)>'
	from /MYMACHOME/.rbenv/versions/2.3.0/gemsets/my_project_in_rails_3/bin/annotate:23:in `load'
	from /MYMACHOME/.rbenv/versions/2.3.0/gemsets/my_project_in_rails_3/bin/annotate:23:in `<main>'
```

Not sure if there's something weird in my app interacting though.
