### ISSUE TITLE
Losing cascade delete option on annotations

### ISSUE THREAD

**Issue by vraravam** [ctran/annotate_models#452]
I was trying to find a fix for the #434, but, when I used the latest commit from the master branch as of now ([8341983](https://github.com/ctran/annotate_models/commit/8341983f263e662c5e528b04d0eeec908daec1ad)), then I get a different error:
```git
-#  fk_customer_metas_customer  (customer_id => users.id) ON DELETE => cascade
+#  fk_customer_metas_customer  (customer_id => users.id)
```
As you can see, the `ON DELETE => cascade` option is completely lost in the annotation - though it is still present in the db.

**Comment by vraravam** [comment]
@ctran - any help in fixing this?

**Comment by sashabelozerov** [comment]
@vraravam Can you please specify version of `activerecord` gem you are using?

**Comment by vraravam** [comment]
@sashabelozerov - im on Rails 5.1.1 - so `activerecord (5.1.1)` is what's in my `Gemfile.lock`
