### ISSUE TITLE
precision on string is sometimes inaccurate 

### ISSUE THREAD

**Issue by luizkowalski** [ctran/annotate_models#457]
in a project here, we are 3 developers. we are using the same ruby version, same postgres version, 2 using MacOS and one using Linux. 
every time a migration is ran, we see changes like this:

```diff
-# *charge_currency*::             <tt>string</tt>
-# *charge_reason*::               <tt>string</tt>
+# *charge_currency*::             <tt>string(255)</tt>
+# *charge_reason*::               <tt>string(255)</tt>
```
that happens for every model and sometimes makes it hard to review PRs. Any idea what could be causing this?

we are using Ruby 2.2.5, Rails 4.2.8 and Annotate 2.7.1

**Comment by ctran** [comment]
Can you paste the schema files obtained from these differences?

**Comment by luizkowalski** [comment]
hmm, I'm afraid I can't, it is a proprietary code, I can't share :(
is there any other way I can help?
