### ISSUE TITLE
It is not compatible with rake 12.0

### ISSUE THREAD

**Issue by calemyers723** [ctran/annotate_models#462]
When I am using latest rails version(5.0.3), I get the following error like this.
Bundler could not find compatible versions for gem "rake":
  In snapshot (Gemfile.lock):
    rake (= 12.0.0)

  In Gemfile:
    annotate was resolved to 2.7.0, which depends on
      rake (< 12.0, >= 10.4)

    rails (~> 5.0.2) was resolved to 5.0.3, which depends on
      railties (= 5.0.3) was resolved to 5.0.3, which depends on
        rake (>= 0.8.7)

The gem is not compatible with rake 12.0
Could you please fix this issue?

Thanks.

**Comment by radeno** [comment]
Use github repository instead rubygems.

But i think there should be new piublished version. Github repo has many important changes.

**Comment by ctran** [comment]
Released - https://rubygems.org/gems/annotate/versions/2.7.2

**Comment by calemyers723** [comment]
@ctran 
Thank you very much.
