### ISSUE TITLE
Annotate does not add default value for `json` fields

### ISSUE THREAD

**Issue by garside** [ctran/annotate_models#463]
We have a table with the following schema (from our `schema.rb` file):

```ruby
  create_table "animals", force: :cascade do |t|
    t.string   "name"
    t.text     "description"
    t.boolean  "use_description", default: false
    t.json     "meta",            default: {}
    t.datetime "created_at"
    t.datetime "updated_at"
  end
```

When we run annotate, we get this in our `app/models/animals.rb` file

```ruby
# == Schema Information
#
# Table name: animals
#
#  id              :integer          not null, primary key
#  name            :string
#  description     :text
#  use_description :boolean          default(FALSE)
#  meta            :json
#  created_at      :datetime
#  updated_at      :datetime
#

class Animal < ActiveRecord::Base
```

Our expectation is that we'd have a `default({})` entry for the `meta` line.

**Comment by shan98** [comment]
Seeing the exact same issue.

**Comment by garside** [comment]
So I pulled down master to maybe author a patch, and found that in the 2.7.1 version there's this hard coded config variable:

```
 63   # Don't show default value for these column types
 64   NO_DEFAULT_COL_TYPES = %w(json jsonb)
```

But in master, this was made into a config that was exposed.

Looks like the gem just isn't up to date with the source?

**Comment by ctran** [comment]
Released - https://rubygems.org/gems/annotate/versions/2.7.2
