### ISSUE TITLE
Release to Rubygems

### ISSUE THREAD

**Issue by radeno** [ctran/annotate_models#466]
Guys,

do you plan to release new version?
You have done many great things as support for Ruby 2.4, Rake 12, new options, support for Rails 5, etc 👍 

Anyway it could be ever more better to use official version instead Git repository. If you do continues deployment as i do it could takes some seconds to deploy new build. Eg. for Docker to install Git or just trivial updating bundle.

**Comment by ctran** [comment]
This is done - https://rubygems.org/gems/annotate/versions/2.7.2
