### ISSUE TITLE
run `annotate` always add a new space

### ISSUE THREAD

**Issue by nmenag** [ctran/annotate_models#472]
when run `annotate` in the console or when run  `rake db:migrate`, always added a new space.

**Comment by b264** [comment]
Could you please show us exactly where this new space is added, with an example?

**Comment by nmenag** [comment]
example de model
![image](https://cloud.githubusercontent.com/assets/4958877/26741133/c65f122c-479d-11e7-9c21-21fa4df6693e.png)

When review the changes in git: 

![image](https://cloud.githubusercontent.com/assets/4958877/26741163/e5022728-479d-11e7-8df8-d2df95f0792b.png)

**Comment by ctran** [comment]
@nmenag, Does this happen to all of your models?

**Comment by nmenag** [comment]
@ctran  yes

**Comment by nmenag** [comment]
@ctran i'm using Postgres 9.6, always added a new line in all the models

**Comment by ctran** [comment]
Dis this happen  with previous  versions as well?
