### ISSUE TITLE
"Model files unchanged" no matter what I do

### ISSUE THREAD

**Issue by alxx** [ctran/annotate_models#480]
Hi,

I've used this gem with no problems on other projects, but this is the first one with Ruby 2.4.1 and Rails 5.1.1.

I get the message "Model files unchanged." for every migration.

I get it even if I run annotate by hand with bundle exec, no matter the arguments (I've tried -m and -f rdoc).

No annotation appears in the models.

Is there a way to run the script verbosely so I can figure out what's wrong?

**Comment by alxx** [comment]
I've dropped the database and all the models and created them from scratch; it seems to work now so I'm closing the ticket.

**Comment by asecondwill** [comment]
got same error.  would rather not drop my db as im doing a lot of data importing.   is there a better way to fix?

**Comment by ctran** [comment]
Try it with "--trace" to see what is causing the problem.

**Comment by nbaryshev** [comment]
I had a similar situation when I tried to add a new column to the scheme. What helped me is I found a migration file and manually deleted it.
After this, I added the field again and then migrated it
e.g.
`rails g migration AddFieldsToUsers firstname:string`
`rake db:migrate`

**Comment by stayce** [comment]
Can confirm, thanks @hazi . I had to delete the annotations from the models after dropping a newly created db.

- ruby 3.1.2p20
- Rails 7.0.3.1
- annotate (3.1.1)
