### ISSUE TITLE
PostgreSQL hash column default not reported on 2.7.2

### ISSUE THREAD

**Issue by reichertm** [ctran/annotate_models#488]
Perhaps this is intended, but the annotation for models containing `default value` on the PostgreSQL `hash` columns have changed.

On 2.7.1 the annotations were
`#  settings                    :hstore           default({})`

On 2.7.2 the annotation are
`#  settings                    :hstore`

**Comment by aarongray** [comment]
Seeing this issue after updating from Rails 4.2 to Rails 5.

**Comment by ctran** [comment]
PR is welcome.
