### ISSUE TITLE
warning: instance variable @loaded_tasks not initialized

### ISSUE THREAD

**Issue by lloeki** [ctran/annotate_models#498]
When running tests on a project depending on annotate_models some warnings are raised (see below).

This is because with a recent rake (>=11.0), ruby warnings are now on by default.

What do you think about fixing those warnings as well as running the test suite with ruby -w ([like this](https://github.com/thoughtbot/shoulda-matchers/blob/2a5c312bcebf561d16577e3db57fbe111dae65df/Rakefile#L10)) ?

```
/Users/lloeki/.gem/ruby/2.3.4/gems/annotate-2.7.2/lib/annotate.rb:124: warning: instance variable @loaded_tasks not initialized
```

**Comment by ctran** [comment]
That's a great idea!  Want to open a PR? :-)
