### ISSUE TITLE
Annotate not leaving empty space after frozen_string_literal:true magic comment

### ISSUE THREAD

**Issue by pachonk** [ctran/annotate_models#509]
Every time I annotate, it removes line of whitespaceI have after my `# frozen_string_literal:true` comment. Is there a configuration that can fix this, or is this a feature I need to build for annotate_models?

**Comment by pachonk** [comment]
Looks like https://github.com/ctran/annotate_models/pull/495 is to fix this issue.

**Comment by b264** [comment]
According to the spec, it has to leave exactly one extra linefeed.  This is currently not configurable, but it could be added here:

https://github.com/ctran/annotate_models/blob/7c8e916db46a1c8678736a33e8df560d536795f0/spec/annotate/annotate_models_spec.rb#L1479-L1501

Also see https://github.com/ctran/annotate_models/issues/464

https://github.com/ctran/annotate_models/pull/495 appears abandoned and is based on older code
