### ISSUE TITLE
Enum hash default value incorrectly annotated

### ISSUE THREAD

**Issue by chuck-john** [ctran/annotate_models#530]
## Description
Annotate is not annotating Rails `#enum` defaults when the field is defined as a hash and the values are integers.

#### Steps to Reproduce
1. Define an integer field with a default of zero
1. Declare the field an `#enum` and pass it a hash with string/symbol keys and integer values.
    For example: `enum role: { user: 1, admin: 2 }`
1. Migrate the database
1. Run `$ annotate`
1. The default value of the enum field will be listed as "NULL"

#### Actual Result
The default column is annotated as "NULL" (see below)
`app/models/user.rb`
<img width="682" alt="annotation" src="https://user-images.githubusercontent.com/1545623/32293483-46c7d224-bf11-11e7-9e5e-5d8aa82fc4fa.png">
`db/schema.rb`
<img width="460" alt="schema" src="https://user-images.githubusercontent.com/1545623/32293493-4db21568-bf11-11e7-82eb-9d2c05128ab6.png">

#### Expected Result
Since the keys of my enum are integers and the database field is an integer, I expect the default value to be an integer.

## Environment
Gem version: 2.7.2

**Comment by ctran** [comment]
I don't think this info is kept in the db.

**Comment by chuck-john** [comment]
True. However, `annotate` is able to recognize default values for string/symbol array enums.

![array annotation](https://user-images.githubusercontent.com/1545623/32328794-155b925a-bfa9-11e7-8d4b-933aad0c52b8.png)
