### ISSUE TITLE
find_by_column_name not working when using annotate gem

### ISSUE THREAD

**Issue by arparthasarathi** [ctran/annotate_models#537]
We have a huge list of rake tasks to be run in which a few are dependent on one another. Every task was running perfectly before using the **annotate** gem. On using this gem in a particular rake task, the ActiveRecord method **find_by_column_name**, for example: find_by_name returns nil, but replacing the above query with **find_by(column_name: value)**, for example: find_by(name: "Joe") works perfectly.

The below code which was working perfectly, now return nil object

`publisher = Publisher.find_by_name("Publisher 1")`

While on replacing the above with the below code works perfectly

`publisher = Publisher.find_by(name: "Publisher 1")`

I am sure that the issue is with this gem because on removing the gem, the former code works with no issues.

Note: **Publisher** model is generated and data is pushed into the table well ahead of this task.

**Comment by arparthasarathi** [comment]
Hi,

Sorry for misleading the issue. The issue is primarily due to the usage of annotate gem.

We have a set of [rake tasks](https://ruby.github.io/rake/) to be run in our development environment. These rake tasks along with **rake db:drop db:create db:migrate** are combined into a single master rake task and run using the command **rake master**. 

When I run the above command, the execution fails.

But when I run the commands separately i.e., **rake db:drop db:create db:migrate** and then **rake master** (without db commands), it executes perfectly.

I am sure that the issue is with **annotate** gem because when I remove the gem, the first command executes perfectly without any issues

**Comment by arparthasarathi** [comment]
Hi @ctran, I hope the issue still persists and haven't got any update on the issue to work upon with. Is there any fix available or way to resolve this?

**Comment by johnpitchko** [comment]
Hey did you see #384 ?
