### ISSUE TITLE
Make the Globalize gem work with annotate

### ISSUE THREAD

**Issue by peterfication** [ctran/annotate_models#541]
Hey there,

thanks a lot for this nice gem. It helps me a lot during development!

In some projects I use the Globalize gem. It translates columns with an additional table, but the interface of the model stays the same. This conflicts with annotate though, because annotate looks at the columns of the model, and the translated columns are removed from there. Hence, the annotations are missing all those translated columns.

This is pretty specific for my use case and not all of the annotate users need this. But I thought I post it here and open it for discussion and if someone has the same problem to find a possible solution.

I made a fork of the project that makes this possible. You can find the changes here: https://github.com/store2be/annotate_models/pull/1/files

What do you think about such a change?

**Comment by ctran** [comment]
Thanks.  I'll take a look at let you know.

**Comment by ctran** [comment]
Sorry for missing this.  If you open a PR with the correct change, I'll merge it.

**Comment by peterfication** [comment]
I made the rebase on the current `develop` branch and created a PR: https://github.com/ctran/annotate_models/pull/602
