### ISSUE TITLE
Is there a release planned ?

### ISSUE THREAD

**Issue by Tuxii** [ctran/annotate_models#547]
Hello,

The last release was on 2 June 2017. There are currently 34 new commits in the `develop` branch. 

Are you planning to merge it into master and release a new version to RubyGems anytime soon ? 

I'm especially interested in https://github.com/ctran/annotate_models/commit/992ad11a924cf7fed7e871de6f9956b52c876925

Thank you for you work.

**Comment by drwl** [comment]
@ctran I can help with the release if you need extra help.

**Comment by ctran** [comment]
@drwl Can you help with getting the release process automated?

**Comment by drwl** [comment]
@KaneMorgan I tried getting to this a while back and this was the response he sent to me
> Take a look at the Release file for the steps I have to do.

I got stuck at the git flow config part but would be happy to work together on this if you're interested.

**Comment by ctran** [comment]
This was released.  I'll make another release this weekend.  The majority of the work is reviewing the resolved issues and make release notes, if someone can help with that, I'll do more frequent releases.
