### ISSUE TITLE
Fixtures base directory setting

### ISSUE THREAD

**Issue by ipmsteven** [ctran/annotate_models#549]
Hi
Is there a way I can set the base directory for my fixtures yml file?

I saw we use the following in [annotate_models.rb](https://github.com/ctran/annotate_models/blob/3cfde3727795efe04c1a62bd5de199e0b01cfff5/lib/annotate/annotate_models.rb#L24)

```ruby
FIXTURE_TEST_DIR = File.join('test', "fixtures")
```
but in my case I put all my `*.yml` fixtures files in `fixtures` directory under `lib`(for sharing fixtures across multiple Rails engines)

**Comment by ctran** [comment]
This is not customizable but PR is welcome.
