### ISSUE TITLE
Suggestion: for --routes

### ISSUE THREAD

**Issue by JoshMLeslie** [ctran/annotate_models#551]
Instead of  '--routes' populating the 'routes.rb' file, it makes more sense to me that it would behave the same way the standard annotate population does, where each controller file is populated w/ its relevant route information at the top.

Unless this optional already exists and I just didn't see it in the docs?

**Comment by ctran** [comment]
This would not be the behavior currently expected.

**Comment by chris-at-jobgetter** [comment]
We would also love to see controllers annotated with routes.
We are constantly switching between routes and controller files looking for orphaned actions
and identifying where / how the action is used

**Comment by ctran** [comment]
PR is welcome.
