### ISSUE TITLE
Preserve whitespace above model annotations

### ISSUE THREAD

**Issue by aceofspades** [ctran/annotate_models#555]
The following is not preserved--the blank line is removed which causes rubocop violations to creep into the repo:

```
# frozen_string_literal: true

# == Schema Information
```

**Comment by arempe93** [comment]
@aceofspades -- if you're using rails and `annotate` is automatically running after migrations, here's something that I do to mitigate the problem in the meantime

Maybe it'll help you as well

In your Rakefile (or lib/tasks)

```ruby
RuboCop::RakeTask.new('rubocop:frozen') do |c|
  c.options = [
    '--auto-correct',
    '--only=Style/FrozenStringLiteralComment,Layout/EmptyLineAfterMagicComment'
  ]
end

namespace :db do
  %i[migrate rollback].each do |cmd|
    task cmd do
      Rake::Task['rubocop:frozen'].invoke
    end

    namespace cmd do
      %i[change up down reset redo].each do |t|
        task t do
          Rake::Task['rubocop:frozen'].invoke
        end
      end
    end
  end
end
```

this will have rubocop autocorrect the `frozen_string_literal` comment and whitespace after `annotate`, without unwittingly auto-correcting anything else

**Comment by aceofspades** [comment]
@arempe93 Thanks. Good thinking. I updated this to run on `app/models spec/models` and also on `db:schem:dump`.
