### ISSUE TITLE
Merge in annotate_gem

### ISSUE THREAD

**Issue by pocheptsov** [ctran/annotate_models#564]
Hi guys, what do you think about integration [annotate_gem](https://github.com/ivantsepp/annotate_gem) into your gem? It's serving similar purpose and well strutured to be easily merged in.

**Comment by ctran** [comment]
What kind of integration?

**Comment by pocheptsov** [comment]
Merge it in.

**Comment by ctran** [comment]
Are you the owner of that gem?

**Comment by pocheptsov** [comment]
Nope, but if interested we can invite @ivantsepp to the conversation.
I can start working on PR if we agree that it's useful.
