### ISSUE TITLE
Can't exclude controller specs

### ISSUE THREAD

**Issue by tsuwatch** [ctran/annotate_models#567]
I exclude controllers from annotation, annotate will still annotate my controller specs.

## Version

- annotate version 2.7.4
- rails version 5.2.0
- ruby version 2.5.1

**Comment by vizcay** [comment]
Hi, I'm on the same boat here, the same problem also with helpers.. I doesn't matters what you put on `lib/tasks/auto_annotate_models.rake` it always annotate those.

* annottate v2.7.4
* rails v4.2.10
* ruby v2.3.3

**Comment by ctran** [comment]
Can you make a test to reproduce this?

**Comment by tsuwatch** [comment]
Sorry, it was my misunderstanding.

**Comment by vizcay** [comment]
@tsuwatch I'm still having the same issue:

* annotate 2.7.4
* rails 4.2.10

I run `rails g annotate:install` to recreate the `auto_annotate_models.rake` file and there I update this:

```
      'exclude_controllers'       => 'true',
      'exclude_helpers'           => 'true',
```

When I run `$ bundle exec rake annotate_models` the schema gets added to the beginning of those. Other options work correctly, for example I was able to set `      'show_foreign_keys'         => 'false',
` without problems.

Any suggestions? Thansk

**Comment by schpet** [comment]
for anyone coming across this in the future, setting `exclude_scaffolds` seems to fix this

```ruby
    Annotate.set_defaults(
      "exclude_tests" => true,
      "exclude_scaffolds" => true
    )
```

https://github.com/ctran/annotate_models/issues/437#issuecomment-310795785

**Comment by vizcay** [comment]
Will be nice to reopen this.

**Comment by ctran** [comment]
You're welcome to submit a PR.

**Comment by justinpchang** [comment]
@ctran I have bandwidth to submit a PR. What do you think the best approach is?

1. Move controller test/spec pattern to match the controller pattern instead of the scaffold pattern.
2. Add controller test/spec pattern to the controller pattern _and keep it in the scaffold pattern_.
3. Update documentation to call out that skipping controller tests/specs can be done with `:exclude_scaffold`.
