### ISSUE TITLE
Inconsistent sorting, annotate failing to recognize changes

### ISSUE THREAD

**Issue by JustinMcDonald** [ctran/annotate_models#568]
We have several models/tables in our application which seem to be failing to annotate properly. For example, Our source code has the following model annotation checked-in for `app/models/example.rb`:

```
# == Schema Information
#
# Table name: examples
#
#  id                                  :integer          not null, primary key
#  abandon                             :boolean
#  ended_at                            :datetime
#
```

When I run `annotate --exclude tests,fixtures,factories,serializers` OR `annotate app/models/example.rb`, there are no annotation changes to the `app/models/example.rb` file. When I run `annotate app/models/example.rb --force`, annotations run and update the file to the following:

```
# == Schema Information
#
# Table name: examples
#
#  id                                  :integer          not null, primary key
#  ended_at                            :datetime
#  abandon                             :boolean
#
```

Running describe on the PostgreSQL table shows that the column ordering does in fact have `ended_at` before `abandon`. I believe the second annotation is the correct one and annotation is failing to recognize that there is a change that needs to be made. It should be updating the annotations even without the `--force` option.

In the README, I see "By default, columns will be sorted in database order (i.e. the order in which migrations were run)." which makes me believe that the annotations should be sorted every time based on the database order, and that sorting is not optional.

I am not using any annotate environment variables.

## Version

- annotate gem version: 2.7.4
- jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 Java HotSpot(TM) 64-Bit Server VM 25.91-b14 on 1.8.0_91-b14 [darwin-x86_64]

**Comment by mesis** [comment]
+1

**Comment by ctran** [comment]
If this is specific to PostGresql, I can only take PR since I don't have the time and environment to reproduce/debug this.

**Comment by drwl** [comment]
@JustinMcDonald is this something you're having issues with? Would you be able to point to an example project so I can reproduce?

**Comment by drwl** [comment]
I'm cleaning up old issues and closing this issue since there hasn't been any activity in a while. Feel free to reopen this if there's any more information that can be provided.
