### ISSUE TITLE
foreign key change of type don't get noticed

### ISSUE THREAD

**Issue by nicktime** [ctran/annotate_models#570]
## Commands

When I change foreign key type from :restrict to :cascade or back
in e.g. Rails migration:
```
      remove_foreign_key :imports, :clients
      add_foreign_key :imports, :clients, on_delete: :cascade
```
then run
`bundle exec annotate`
I get 
`Model files unchanged.`
And it's at outdated
```
# Foreign Keys
#
#  fk_rails_...  (client_id => clients.id) ON DELETE => restrict
```
Only running with --force updates them properly.

## Version

- annotate v2.7.4
- Rails 5.2.0
- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

**Comment by ctran** [comment]
Is it possible to give me a complete model to reproduce this?  Even better if you can update one of the existing test cases.

**Comment by nicktime** [comment]
Ok, I'll try to add a test for this.

**Comment by nicktime** [comment]
Done.

**Comment by drwl** [comment]
@nicktime So the test added in #601 highlights a bug that needs to be addressed?

**Comment by nicktime** [comment]
@drwl That's right.

**Comment by drwl** [comment]
Thanks for adding the test. I've marked this as a bug and will wait off on merging the test until there's an appropriate fix, as otherwise it'll fail builds going forward.

**Comment by nicktime** [comment]
Sure, you're welcome.
