### ISSUE TITLE
new lines between annotation and module definition

### ISSUE THREAD

**Issue by dudo** [ctran/annotate_models#577]
# ...
    #
    

    module
      ..

Rubocop is yelling about the 2 new lines between the comments and the start of the module/class. Anyway to control that?

**Comment by dudo** [comment]
This is exactly the issue I was seeing with #578

**Comment by kreintjes** [comment]
I'm having the same issue, but I don't believe it is fixed by #578. That seems to be a different problem. How can we remove the multiple empty lines after the annotation comments?
