### ISSUE TITLE
Any(?) errors in any files on the build path produce impossible-to-decipher error on annotate

### ISSUE THREAD

**Issue by joshk6** [ctran/annotate_models#582]
Describe your problem here.
It took me some time to figure out that a PORO that has nothing to do with activerecord which has a compile error will kill annotate with a indecipherable message:
I executed annotate on the terminal and got this result.
4b301d49d2d% annotate
/[...]/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations/clusivity.rb:8: warning: already initialized constant ActiveModel::Validations::Clusivity::ERROR_MESSAGE
/Users/jkramer/.rvm/gems/ruby-2.4.2@global/gems/activemodel-5.2.1/lib/active_model/validations/clusivity.rb:8: warning: previous definition of ERROR_MESSAGE was here

This error went away when I fixed the error, which was in a file under app/, in a custom directory.  .  Somehow alerting users what this error may be a result of would be helpful if possible, as it was non-intuitive (to me at least) that an error in a random file unrelated to annotate would be responsible.     Thanks.
 
- annotate version 2.7.4
- rails version 5.2.1
- ruby version 2.4.2

**Comment by drwl** [comment]
@joshk6 if this is still an issue, could you provide an example project repository where we could replicate it?

**Comment by drwl** [comment]
Closing this out -- feel free to reopen if you still have this problem and can add more information.
