### ISSUE TITLE
rbenv: version `2.5.1' is not installed (set by /Users/acpk/documents/websites/foundation/.ruby-version)

### ISSUE THREAD

**Issue by ACPK** [ctran/annotate_models#583]
When running the command below, I get the error:

    rbenv: version `2.5.1' is not installed (set by /Users/acpk/documents/websites/foundation/.ruby-version)

```
$ annotate --exclude tests,fixtures,factories,serializers
```
Annotate 2.7.4
Rails 5.2.1
Ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by ctran** [comment]
This looks like a version in your rbenv setup?
