### ISSUE TITLE
Double empty lines after annotate comments gives Rubocop error

### ISSUE THREAD

**Issue by kreintjes** [ctran/annotate_models#591]
The gem adds multiple empty lines after the annotate command in models when using the bare format. Rubocop doesn't like that (`Layout/EmptyLines: Extra blank line detected`). You can't even fix that with `rubocop:disable` in the open wrapper and `rubocop:enable` in the close wrapper, since the close wrapper is added before the extra whitespace.

Example output for a model account.rb:

```
# frozen_string_literal: true

# rubocop:disable Layout/EmptyLines
# == Schema Information
#
# Table name: accounts
#
#  id                         :integer          not null, primary key
#
# rubocop:enable Layout/EmptyLines
 
 
class Account < ApplicationRecord
  ....
end
```

## Version

- annotate version: 2.7.4
- rails version: 5.2.1
- ruby version: 2.5.1

**Comment by NikoRoberts** [comment]
With the setting `'position_in_class'       => 'bottom',` this ends up continuously adding new lines at the top of classses every time you run `db:migrate`

**Comment by NikoRoberts** [comment]
It looks like PR #552 would fix this

**Comment by kreintjes** [comment]
@NikoRoberts I did not see that PR, thanks. I just tried it and it indeed removes the extra empty line after the annotations, but unfortunately also removes the empty line between the frozen_string_literal magic comment on top of the file and the annotations below it, resulting in another RuboCop violation.

**Comment by NikoRoberts** [comment]
I had a bit of a go today trying to merge the latest changes with that branch but the latest changes conflict a lot.
I'll see if I can merge both and not end up with any rubocop violations

**Comment by kreintjes** [comment]
@NikoRoberts any progress on this?

**Comment by NikoRoberts** [comment]
No luck. I went back to manually removing the lines every time I run migrate :'(
It isn't quite causing me enough pain yet
