### ISSUE TITLE
Annotate arbitrary files using a file matcher?

### ISSUE THREAD

**Issue by grapevinegizmos** [ctran/annotate_models#594]
Tremendously useful gem.  Many thanks.

I was wondering if you might consider for the next iteration some possibility to annotate other relevant files other than the ones you've already provided for.  For example, have a workflows directory where i put model functions in order not to bloat the models or controllers themselves with a lot of business logic.   

So if I have a model called Foo, I have a FooWorkflow object in my workflows directory, which I call from controller code or model code as appropriate.    It would be swell if I could use annotate to insert the model definition in the relevant workflow file.

Perhaps if there were some config command where you could specify some kind of regex like matcher e.g. {ModelName}_workflow.rb and it would annotate all the files that matched.

## Commands

```
$ show your commands here.
```

## Version

- annotate version
- rails version
- ruby version

**Comment by ctran** [comment]
This seems pretty straight forward to add, if you want to take a crack at it:
> https://github.com/ctran/annotate_models/blob/develop/lib/annotate/annotate_models.rb#L781
