### ISSUE TITLE
Compatibility with data_migrate gem

### ISSUE THREAD

**Issue by yiweig** [ctran/annotate_models#600]
The [data-migrate](https://github.com/ilyakatz/data-migrate) gem adds data migrations via `rake db:migrate:with_data` (among others) but it seems that this annotate gem is only triggered when the vanilla version of `db:migrate` is run. 

I'm new to the Ruby/Rails world, and was wondering what the suggested way to make these two gems compatible would be. Are you open to PRs? I'd be happy to take a shot at adding the data-migrate gem's commands to https://github.com/ctran/annotate_models/blob/develop/lib/tasks/annotate_models_migrate.rake, if that's the "proper" way to do things.

Another suggestion I've seen on SO seems to be adding a custom invocation to my own `Rakefile`, but I'm not sure how kosher it is in the RoR community to use that file for things like this.

**Comment by ctran** [comment]
The kosher way is to have your own Rakefile.  It doesn't make sense to couple these gems.

**Comment by yiweig** [comment]
@ctran cool, thanks for the tip there. I'll close this.
