### ISSUE TITLE
Incorrect tag `2.7.5`?

### ISSUE THREAD

**Issue by ybiquitous** [ctran/annotate_models#617]
It seems that the `2.7.5` tag is incorrect for `v2.7.5`. 🤔 

[![Image from Gyazo](https://i.gyazo.com/46a7f0c9f90e91e4a75a56517f3595be.gif)](https://gyazo.com/46a7f0c9f90e91e4a75a56517f3595be)

Changelog:
https://github.com/ctran/annotate_models/blob/289621b82c8f1a6a56c0882d4ea34aabd722fcdf/CHANGELOG.rdoc

Not found page:
https://github.com/ctran/annotate_models/releases/tag/v2.7.5

**Comment by drwl** [comment]
Good catch. It looks like it's fixed now.

**Comment by ybiquitous** [comment]
Thank you! 😊
