### ISSUE TITLE
undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by vnbrs** [ctran/annotate_models#620]
Hi!

First of all, thank you for this really useful gem that is a must in my Rails projects.

I've been messing up with Rails 6, and when I created a new migration/model and tried to annotate the files, it seems something got wrong, as you can see in the error messages below.

Here's my migration file:

```ruby
class CreateSheep < ActiveRecord::Migration[6.0]
  def change
    create_table :sheep do |t|
      t.string :name
      t.date :date_of_birth
      t.references :address, null: true, foreign_key: true
      t.string :phone_number

      t.timestamps
    end
  end
end

```

And the model:

```ruby
class Sheep < ApplicationRecord
  belongs_to :address
end
```

The migration ran fine, but is it something wrong I'm doing?

## Commands

```sh
$ bundle exec annotate
#> Unable to annotate app/models/sheep.rb: undefined method `gsub' for nil:NilClass
#> Unable to annotate app/models/sheep.rb: no implicit conversion of nil into Array
#> Model files unchanged.
```

## Version

- annotate version: tried with branch develop and master
- rails version: 6.0.0.rc1
- ruby version: 2.6.3

**Comment by kamil98** [comment]
shouldn't the table name be in plural form?

**Comment by drwl** [comment]
@vnbrs is this still an issue you have? If so, I would try @kamil98's advice and make the migration create the table using the plural form. I haven't used Rails 6, however I don't think this is an annotate issue.

**Comment by vnbrs** [comment]
@kamil98 @drwl Hey! Thanks for the help. Unfortunately, this is still an issue. The thing is, the plural of sheep is sheep.

**Comment by posiczko-stateless** [comment]
Hello,

I have the same experience as @vnbrs in MRI 2.6.4 and Rails 6.0.0.

The issue seems to be related to the foreign keys when using `references` in migrations:

```shell
rails new blog-with-comments \
      --skip-action-mailer \
      --skip-active-storage \
      --skip-action-cable \
      --skip-test \
      --skip-spring \
      --skip-webpack-install

cd blog-with-comments
echo "gem 'annotate'" >> Gemfile
bundle
rails g annotate:install

rails g resource post title:string content:text
# annotation works
rails db:migrate

rails g resource comment rating:integer comment:text post:references
# annotation does not work
rails db:migrate
```
The last migration calling annotation results in

```
~/blog-with-comments master*
❯ rails db:migrate

RAILS_ENV=development environment is not defined in config/webpacker.yml, falling back to production environment
== 20190908134429 CreateComments: migrating ===================================
-- create_table(:comments)
   -> 0.0031s
== 20190908134429 CreateComments: migrated (0.0032s) ==========================

Unable to annotate app/models/comment.rb: undefined method `gsub' for nil:NilClass
Unable to annotate app/models/comment.rb: no implicit conversion of nil into Array
Model files unchanged.

~/blog-with-comments master*
```

Thank you for a very useful gem!

Pawel

**Comment by afittro** [comment]
Any updates? This is still an issue and still affected by references in migrations. Rails 6.0.1, Ruby 2.6.5, Annotate 3.0.3

**Comment by drwl** [comment]
Hi folks, I merged in #695 can yall try using what's in the develop branch? 

cc @vnbrs @posiczko-stateless @afittro

**Comment by afittro** [comment]
-I updated my Gemfile:  gem 'annotate', git: 'https://github.com/ctran/annotate_models'
-I ran bundle update
-I ran bundle exec annotate
For each model, I got this:
Unable to annotate app/models/mymodel.rb: undefined method `gsub' for nil:NilClass
Unable to annotate app/models/mymodel.rb: no implicit conversion of nil into Array
-followed by "model files unchanged"

**Comment by daveshah** [comment]
Just ran into this issue on Rails 6.0.1 when adding, then running a new migration.
I updated my Gemfile to:
```
gem 'annotate', git: 'git@github.com:ctran/annotate_models.git', branch: 'develop'
```
This resolved the issue for me 👍 
@afittro - in your comment above, you don't have the branch specified. Did you omit this in the Gemfile?

**Comment by afittro** [comment]
@daveshah that was it. Apologies for the oversight. Annotate now works as advertised again!

**Comment by drwl** [comment]
Thanks everyone for chiming in and helping others, really nice to see the open source community help out! It seems like this issue is fixed, going to close it out. 

Feel free to reopen if I've misread the thread.
