### ISSUE TITLE
Negative argument in mb_chars_ljust for columns with long types

### ISSUE THREAD

**Issue by colbymelvin** [ctran/annotate_models#621]
Hello! Thank you for creating a very valuable tool. My workplace uses annotate_models on a near daily basis.

After upgrading to 2.7.5 recently, we have noticed that the annotations fail for some files, and not others. After some digging, I came across [this commit](https://github.com/ctran/annotate_models/commit/26142667a1da560e681fc0621857a160edf26007) which added the `mb_chars_ljust` method.

It seems as if that method is currently making an assumption that `padding` will be 0 or positive. This should always be true for column names, because of the `max_size` logic. However, it is not always true for columns with large types. The `format_default` method calls `mb_chars_ljust` with the column's type and `bare_type_allowance`, which is hard-coded to `16`. This can give us a negative padding when subtracting the length of the `col_type` string from `bare_type_allowance` if the length of `col_type` is greater than 16. This results in the throwing of an `ArgumentError: negative argument` when attempting to compute the padding to be added to the string.

My workplace uses the [activerecord-postgis-adapter](https://github.com/rgeo/activerecord-postgis-adapter), which exposes several data types larger than 16 characters. Whenever we use one of these data types in a model, we can no longer annotate said model.

## Commands

```
$ annotate
...
> Unable to annotate app/models/some_model.rb: negative argument
...
```

## Version

- annotate version
2.7.5

- rails version
5.2.3

- ruby version
2.5.5

**Comment by colbymelvin** [comment]
I have a fix [here](https://github.com/colbymelvin/annotate_models/commit/e66f98f095167d3524c2a6bfe202d095fc7f6737), and would like to submit a PR.

**Comment by drwl** [comment]
@colbymelvin I believe this should be working as of 2.7.5. Would you mind confirming?

**Comment by colbymelvin** [comment]
@drwl Confirmed - My org is no longer pointed at my fork! Thanks :)

**Comment by drwl** [comment]
Cool 😎gonna close this out.
