### ISSUE TITLE
Using annotations to create database tables?

### ISSUE THREAD

**Issue by tfreedman** [ctran/annotate_models#632]
The comments that annotate_models produces are super useful, and I can manually create a database table with them. I'm wondering if there's any automated way to read all the annotations in and recreate database tables if they don't exist, as an alternative to using migrations / schema.rb?

**Comment by drwl** [comment]
I imagine it would be possible, however that would be out of the scope of this gem's functionality.

**Comment by drwl** [comment]
Going to be closing issue. If you feel that it's wrongly closed please comment and reply.
