### ISSUE TITLE
Support for Rails 6

### ISSUE THREAD

**Issue by andrepcg** [ctran/annotate_models#651]
Are you planning on supporting Rails 6 (and thus activerecord 6) soon?

What needs to be done in order to support such versions?

**Comment by KelseyDH** [comment]
Is it breaking right now?

**Comment by andrepcg** [comment]
@KelseyDH It's not but the gemfile imposes restrictions on the gems versions and activerecord is set to LESS than 6, not including

**Comment by KelseyDH** [comment]
Are you sure this is still an issue?  The latest gem code shows:

```
  s.add_runtime_dependency(%q<activerecord>, ['>= 3.2', '< 7.0'])
```

It appears this is in the latest release also, so I think you just need to update your annotate gem.

**Comment by drwl** [comment]
@andrepcg could you provide more information? If you could use the template that would be great.

# The Template:

Describe your problem here.

## Commands

```
$ show your commands here.
```

## Version

- annotate version
- rails version
- ruby version

**Comment by andrepcg** [comment]
Well that's weird because the last time I tried to install it complained about my activerecord version being too high. Just tried right now and works fine
