### ISSUE TITLE
LoadError: cannot load such file -- annotate/parser

### ISSUE THREAD

**Issue by 9mm** [ctran/annotate_models#657]
2.7.x worked fine but 3.0 on rails 6 gives me an error:

```
LoadError: cannot load such file -- annotate/parser
  /Users/Z/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/annotate-3.0.0/bin/annotate:18:in `require'
  /Users/Z/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/annotate-3.0.0/bin/annotate:18:in `<top (required)>'
  /Users/Z/.rbenv/versions/2.6.4/bin/annotate:23:in `load'
  /Users/Z/.rbenv/versions/2.6.4/bin/annotate:23:in `<top (required)>'
```

## Commands

```
$ bundle exec annotate
```

## Version

- annotate version: 3.0
- rails version 6.0.0
- ruby version 2.6.4

**Comment by kapso** [comment]
Yea getting the same issue with those versions.

**Comment by coderberry** [comment]
Same

**Comment by TedTran2019** [comment]
Oh man, I thought I was insane. I was trying everything to get it to work, but it wouldn't.

I'm on Ruby 2.6.4, Rails 6.0, and annotate 3.0.0 and I get the exact same error.

**Comment by drwl** [comment]
Will take a look, thanks for the report.

**Comment by drwl** [comment]
Will close this when `3.0.1` gets released.

**Comment by drwl** [comment]
Released `3.0.2`, @9mm can you confirm?

**Comment by 9mm** [comment]
I’m not at computer right now but I tested yesterday using master branch and it worked :) so I assume it’s good now. Thanks!

**Comment by 9mm** [comment]
It works 👌🏼
