### ISSUE TITLE
Update rake dependency

### ISSUE THREAD

**Issue by richard-viney** [ctran/annotate_models#666]
As of annotate 3.0.2 the rake dependency in the Gemspec specifies `< 13`. However, rake 13.0 was recently released and the only breaking change was dropping Ruby versions prior to 2.2. See https://github.com/ruby/rake/blob/master/History.rdoc.

Relaxing this version cap to `< 14` should be safe to do and would allow apps to use the latest version of rake.

Thanks!

## Version

- annotate 3.0.2
- rails 6.0.0
- ruby 2.5.3p105

**Comment by drwl** [comment]
@richard-viney thanks for reporting, I just merged in #659 so `develop` branch should be able to work for now.

**Comment by openscript** [comment]
The annotate gem forced my environment to downgrade the rake version, which broke my test environment.
```
Gem::LoadError: You have already activated rake 13.0.0, but your Gemfile requires rake 12.3.3. Prepending `bundle exec` to your command may solve this.
```
I confirm that #659 fixes the issue! :+1: 

Thank you :)

**Comment by drwl** [comment]
I cut a release for 3.0.3 that includes PR #659 so let me know if that doesn't work. @openscript @richard-viney

**Comment by drwl** [comment]
Seems like it works so closing this for now. Feel free to reopen.
