### ISSUE TITLE
Newest version with rake fix was not published

### ISSUE THREAD

**Issue by manme** [ctran/annotate_models#673]
Describe your problem here.

## Version

newest annotate version `release/3.0.1` was not published on rubygems, could we solve this issue?

**Comment by rhiroshi** [comment]
3.0.1 [was not released](https://github.com/ctran/annotate_models/blob/develop/CHANGELOG.rdoc) and rubygems is at 3.0.2

**Comment by manme** [comment]
Yes, but 3.0.1 is more fresh than 3.0.2 specially I see it by gemspec file, 3.0.1 supports rake Version up to 14, and 3.0.2 up to 13. Also in releases it’s visible that 3.0.1 is more fresh

**Comment by drwl** [comment]
@manme @rhiroshi just pushed pushed 3.0.3 to Rubygems with the rake dependency fix.
