### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by softwaregravy** [ctran/annotate_models#680]
I'm seeing deprecation warnings for ::Fixnum and ::Bignum

## Commands

```
annotate
.../gems/annotate-2.6.5/lib/annotate/annotate_models.rb:77: warning: constant ::Fixnum is deprecated
.../gems/annotate-2.6.5/lib/annotate/annotate_models.rb:77: warning: constant ::Bignum is deprecated
```

## Version

Annotate 2.6.5
Ruby 2.6.5
Rails 5.2.3

**Comment by drwl** [comment]
@softwaregravy looks like you're using an older version of Annotate as it gets patched later in https://github.com/ctran/annotate_models/pull/415.

**Comment by softwaregravy** [comment]
thank you
