### ISSUE TITLE
Migrating off of TravisCI

### ISSUE THREAD

**Issue by drwl** [ctran/annotate_models#683]
Github Actions provides a way for us to automatically run CI and cut releases. @ctran has made progress on this. We want to migrate off of Travis as it's redundant. 

Happy to collaborate with any folk(s) that want to take this on.

**Comment by drwl** [comment]
In my research I've found that Github Actions is currently not mature enough yet to handle the needs of the project. Things that would be nice to have:

- caching of ruby images
- being able to select ruby versions

So for the time being TravisCI will be here to stay.

**Comment by drwl** [comment]
Also need to setup RVM in Github CI to run integration tests.

**Comment by olleolleolle** [comment]
This seems _done_, now!
