### ISSUE TITLE
bundle install failled on annotate_models

### ISSUE THREAD

**Issue by Tectract** [ctran/annotate_models#688]
Fetching git://github.com/ctran/annotate_models.git
fatal: Could not parse object 'c952306966c9bae4438e4d40351561af3d8005c0'.
Revision c952306966c9bae4438e4d40351561af3d8005c0 does not exist in the repository
git://github.com/ctran/annotate_models.git. Maybe you misspelled it?

## Commands

`bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment`

## Version

`gem 'annotate', github: 'ctran/annotate_models'`

- annotate version

```
GIT
  remote: git://github.com/ctran/annotate_models.git
  revision: c952306966c9bae4438e4d40351561af3d8005c0
  specs:
    annotate (2.7.0)
      activerecord (>= 3.2, < 6.0)
      rake (>= 10.4, < 12.0)
```

- rails version
4.2.10

- ruby version
2.4.5

**Comment by drwl** [comment]
@Tectract I'm not sure I have enough information to help. Could you post your file Gemfile?

**Comment by drwl** [comment]
@tectract gonna close this out due to inactivity. Feel free to reopen and tag me if there are any updates with posting your gemfile or if your situation has been resolved.
