### ISSUE TITLE
Version 3.1.1 not released?

### ISSUE THREAD

**Issue by JanStevens** [ctran/annotate_models#775]
Hello 👋 

Trying to upgrade to latest version 3.1.1 so the default annotations are back ok but it seems like the Gem is not released? I see there is a change log and a tag

## Commands

```
bundle install
Fetching gem metadata from https://gems.playpass.eu/..
Could not find gem 'annotate (= 3.1.1)' in any of the gem sources listed in your Gemfile.
```

## Version

- annotate version: 3.1.0
- rails version: ~> 5.2.4
- ruby version: 2.6.5

**Comment by pcraston** [comment]
Yeah would be great if it could be released asap! 👍

**Comment by drwl** [comment]
Hi all I apologize on the delay. There was an issue with our travis.yml config that prevented release job from happening. It's live now per https://rubygems.org/gems/annotate/.

**Comment by drwl** [comment]
Closing this out as it's released. Feel free to reopen.
