### ISSUE TITLE
Annotation support for Rails 6+ Multiple Database

### ISSUE THREAD

**Issue by geetfun** [ctran/annotate_models#815]
Apologies if this has been brought up, but I couldn't seem to find it. In Rails 6 (https://guides.rubyonrails.org/active_record_multiple_databases.html), there is support for multiple databases. 

I noticed that annotate_models does not annotate models that's in a non-primary database.

## Version

- annotate version (latest)
- rails version (Rails 6 current, 6.0.3.1)
- ruby 2.7.1

**Comment by leonid-shevtsov** [comment]
Weird - for me it _does_ annotate all the models, _but_ confuses models with the same name that belong to different databases.

**Comment by geetfun** [comment]
@leonid-shevtsov Great timing! Turned out I had misconfigured annotate. Fixed it and came back to update this.

**Comment by xcskier56** [comment]
@leonid-shevtsov any tips on how to deal with models of the same name that belong to different databases? Aside from renaming obviously
