### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by nard-tech** [ctran/annotate_models#859]
When I merged the latest `develop` branch to #793, CI failed.

I tried to fix this problems in #858, but I could not fix it.

In order to inspect causes, I added empty commit (cf. b5a930b in #858), and CI failed, while in #855 (merge commit for the latest `develop`) CI succeed.

As https://github.com/ctran/annotate_models/runs/2226347966 shows, there seems to be several causes.

## Version

- annotate version: 3.1.1
- rails version: 5.2.4.1, 6.0.2.1
- ruby version: 2.4, 2.5, 2.6

**Comment by ctran** [comment]
See https://github.com/ctran/annotate_models/pull/959
