### ISSUE TITLE
Annotate fails when is used module table_name_prefix

### ISSUE THREAD

**Issue by radeno** [ctran/annotate_models#92]
Hi,

annotable_models are very handy and easy to use gem (maybe rake task will be easier because have list [rake -T]).

This issue is about that it really great works on "standard" models but not on models within namespace and defined with table_name_prefix.

for example:

``` ruby
module Order
  def self.table_name_prefix
    'order_'
  end
end
```

and nested model

``` ruby
module Order
  class Item < ActiveRecord::Base
  end
end
```

Annotate models search in table `items` which not exists and right is `order_items`

**Comment by drewlustro** [comment]
I'm experiencing this issue on latest version `3.1.1`
