### ISSUE TITLE
Update rubygems.org version to work with Rails 7

### ISSUE THREAD

**Issue by brtrick** [ctran/annotate_models#932]
The annotate version on rubygems.org is still set to activerecord < 7.0. It would be a great help if rubygems could be updated with the latest fixes. Thank you!

**Comment by barrywoolgar** [comment]
I was able to update to 3.2 today, it has the `< 8.0` requirement.

**Comment by brtrick** [comment]
Yes, thank you, it is working now. Closing this issue.
