### ISSUE TITLE
Make `with_comment_column` work with `Annotate.set_defaults`

### ISSUE THREAD

**Issue by Adeynack** [ctran/annotate_models#990]
Describe your problem here.

## Commands

```
$ rake annotate_models
```

## Acceptance Criteria

- `"with_comment_column" => "false"` appears after `"with_comment" => "false"` when calling `rails generate annotate:install`.
- its setting is read when annotating (right now, setting it to `true` does not activate the switch and comment column is not rendered).

## Related Issues

This was an oversight when implementing #988.

**Comment by Adeynack** [comment]
@ctran : You can assign me on this. I will work to fix it.

**Comment by ctran** [comment]
Thanks

**Comment by sureshc** [comment]
Any progress on this? We have [a few long table column comments](https://github.com/code-dot-org/code-dot-org/blob/c761a4291bc0d2f220639aec9c513c1afe0f0a25/dashboard/db/schema.rb#L424) and having this option work with `.set_defaults` would make the annotations more readable. We can't really turn on `with_comment` because of the formatting.

**Comment by Adeynack** [comment]
To be 💯 honest, that slipped my mind completely. But I'll resume my effort here, especially if it can make other's life easier! Thanks for the reminder ;-)

**Comment by sureshc** [comment]
> To be 💯 honest, that slipped my mind completely. But I'll resume my effort here, especially if it can make other's life easier! Thanks for the reminder ;-)

Thank you so much. We very much appreciate this gem.

**Comment by Adeynack** [comment]
@sureshc @ctran : If I am not mistaken, #999 should do the trick :-)

**Comment by Adeynack** [comment]
@ctran : When can we expect a release with this feature added? 😊
